### ISSUE TITLE
Viewer: improvements tracking bug

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1108]
General
- [ ] TESTS!
- [x] refactor code into modules
- [x] upstream share button to the core report, show/hide it using report-context in css.

UX
- [x] figure out how to handler older reports.
- [ ] making sharing more obvious
- [ ] reuse existing .json gist if one exists.
- [x] update `<title>` on report load/change.
- [ ] implement signout flow
- [ ] handle case where the user deletes IDB (and therefore their saved GH token) or revokes their access on github.
- [ ] handle back/forward navigation. URL should always match the view.

Perf
- [x] lazyload the report.css or combine with viewer.css
- [x] lazy load polyfills when needed
- [ ] Use rollup to remove unused code from the bundle. Slim. It. Down.
- [ ] Lazy load firebase and github code on demand

**Comment by wardpeet** [comment]
maybe add some tests to it as well :)

**Comment by brendankenny** [comment]
tests for this would be great to make sure we don't break ourselves. Really easy to break the extension on master with random PRs that are only caught when we near a release.

Short of breaking out selenium or whatever, we could expose a pure JS end point so we could test that this is working (in coordination with more report generation tests)

**Comment by ebidel** [comment]
@wardpeet no reason in particular. I just know rollup using es6 modules, does tree shaking, and is pretty minimal in what it generates. Does webpack2 produce a slimmer output than v1? 

How about tests in a followup PR? The current one is getting quite large.  Tests can be tackled by beefing up the existing report tests in lighthouse-core and then testing the additional functionality that the viewer adds on top of the report.

**Comment by brendankenny** [comment]
yeah, I meant tests as part of the list in #1108 for future improvements

**Comment by ebidel** [comment]
Added to top of list!

**Comment by paulirish** [comment]
In this state, you should not show the drop message, since we know we're loading from network instead:

![image](https://cloud.githubusercontent.com/assets/39191/20908181/d6445648-bb07-11e6-8619-8639cbf0f157.png)

**Comment by paulirish** [comment]
Since this report is already saved to a GIST, it doesn't seem like the share icon should attempt to resave it to another gist.
![image](https://cloud.githubusercontent.com/assets/39191/20908198/0c72bb88-bb08-11e6-8796-8786b23775cb.png)

**Comment by wardpeet** [comment]
@ebidel webpack2 also does tree shaking making the bundle smaller than webpack 1. When using webpack 2 we can ditch browserify as well. Downside is that webpack is modular and we load more dependencies in.

**Comment by ebidel** [comment]
Most of this is taken care of. Adding some tests now.
