### ISSUE TITLE
☂️ 👣 Breaking changes for v7

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#11207]
A collection place of breaking changes we'd like to make in v7 that might not deserve a separate issue. If you come across any API that would be nice to change, add it here :) 

If the list never gets long we can convert of close in favor of a regular v7 burndown list once it gets closer.

**Targeted**

- [x] `ImageElements`: update artifact shape #11642
- [x] nodejs: drop support for [Node <12](https://nodejs.org/en/about/releases/). #11656
  - Will get us [`Intl.NumberFormat` units](https://v8.dev/features/intl-numberformat#units)!
- [x] details types: split node details to subproperty https://github.com/GoogleChrome/lighthouse/pull/11474
- [x] axe-core: update and evaluate all the enabled checks #11661
- [x] fullyLoaded: wait for images for LCP (possibly more?) #11180 #11639 

**Perhaps v7**
- [x] `consoleAPI` entries in `ConsoleMessages` artifact #11597
- [x] emulation: shift around emulation flags #10910 

**Punt to v8**

- [ ] possibly recalibrate throttling multipliers? #9085 
- [ ] redirects performance consistency observed v. simulated https://github.com/GoogleChrome/lighthouse/issues/8984
