### ISSUE TITLE
 Flow Support (Fraggle Rock)

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#11313]
## Summary

Lighthouse is going to slowly introduce support for running on flows, i.e. situations beyond just the initial page load. This issue collects related discussions we've had on this topic in the past, describes the rough roadmap and milestones, and links to relevant design documents as they're written.

## Scope

Four core scenarios to eventually support.

- Run snapshot-style audits on a page after interaction, i.e. I've clicked a menu option and now rerun the accessibility category
- Run timespan-style audits on a page *during* any arbitrary interaction 
- Run Lighthouse on a traditional page navigation *from an existing page*
- Run Lighthouse on a single page app navigation

### Phase 0 - Research & Design
- [x] Create an inventory of all audits cataloging their implicit requirements (e.g. snapshot v. timespan v. load) [Complete](https://docs.google.com/spreadsheets/u/1/d/1d1oG67eoJWRKMBsYDNMT510_b9J0mPetxsL277k-Jtc/edit?usp=sharing)
- [x] Create design doc and project plan [Complete](https://docs.google.com/document/d/1fRCh_NVK82YmIi1Zq8y73_p79d-FdnKsvaxMy0xIpNw/edit#)

### Phase 1 - Basic End-to-End FR Structure

- [x] refactor runner to expose shared components https://github.com/GoogleChrome/lighthouse/pull/11623
- [x] create a driver v2 based on puppeteer page object #11742
  - [x] add more limited `TransitionalGatherer` and `TransitionalDriver` types that any gatherer supporting FR must use instead of default gatherer (with full access to driver and `loadData`) #11742 #11743
- [x] create a fraggle rock runner that collects afterPass artifacts only #11748
  - [x] add `-pptrtest.js` suite support that runs separately from unit but can use real chrome and test puppeteer use cases #11748

### Phase 2 - Configuration Support, Snapshot mode

- [x] create a barebones config v2 that supports artifact definition at the root #11915
- [x] refactor all to-be-shared config logic out of config.js into config-helpers.js #11759 #11915
- [x] introduce gatherer `.meta` that can annotate gatherers with their supported mode #11917
- [x] refactor gatherers that support snapshot mode to expose a `snapshot` method to return the artifact #11917
- [x] add config v2 functionality to filter down to snapshot mode #11941 

### Phase 3 - Timespan mode

- [x] create a basic timespan mode entrypoint in fraggle rock API #11944
    - [x] upgrade the default base gatherer with timespan methods #11944
    - [x] upgrade 1 gatherer (ConsoleMessages might be easiest?) to work with new fraggle rock timespan #11944
    - [x] add the entrypoint method #11944
    - [x] split logic out of `api.js` into `gather/snapshot-runner`/`gather/timespan-runner` #11944

### Phase 4 - Navigation mode

- [x] add navigations definition to config
- [x] create minimal navigation mode entrypoint in fraggle rock API
  - [x] skip almost all logic, artifacts and puppeteer APIs only
- [x] create `DevToolsLog` gatherer 
    - [x] extend FR session to handle `onAny()`
    - [x] expose networkmonitor object on driver / create status monitor on top of recorder
        - [x] cleanup recordFromLogs/getRecords/getRawRecords
- [x] enable non-standard artifact parity
    - [x] add artifact dependency support to config (definition) and runners (sequencing)
    - [x] covert base artifacts to actual artifacts
    - [x] create `Trace` gatherer and `traces` shim artifact
    - [x] create `devtoolsLogs` shim artifact
- [x] reshape navigation mode to match more of gather-runner, FR-COMPAT annotations
    - [x] expose execution context on driver instead of delegate
    - [x] extract driver shared logic @patrickhulce 
      - [x] enableRuntime/enableAsyncStacks @patrickhulce 
      - [x] register page-side listeners and cached natives @patrickhulce 
      - [x] clearDataForOrigin / storage warning @patrickhulce 
      - [x] setThrottling @patrickhulce 
    - [x] extract gather-runner shared logic @patrickhulce 
        - [x] navigation @patrickhulce 
        - [x] driver setup (JS dialogs, rIC wrap, etc)
        - [x] phase setup (throttling, scroll position, etc)
        - [x] navigation page load errors
        - [x] slow CPU warning
        - [x] base artifacts
- [x] filter out manual audits in empty categories

### Phase 5 - Audit/Artifact upgrading
Goals: Internal refactoring to make places that require a page load more explicit, remove assumptions. (e.g. #11034 #11253 etc)
Goal: Match real-world navigation mode usecases (waitFor conditions, real network monitor stuff)

This part is parallelizable and work likely distributed among the team.

- [x] support TraceOfTab in timespan mode @patrickhulce 
    - [x] add gatherMode to audit context @patrickhulce 
    - [x] conditionally use main-thread identification depending on mode @patrickhulce 
- [x] annotate/upgrade all the gatherers 🎉 see [gatherer burndown assignments](https://docs.google.com/spreadsheets/d/1d1oG67eoJWRKMBsYDNMT510_b9J0mPetxsL277k-Jtc/edit#gid=1289369769)
- [x] mark audits with violating invariants as notApplicable, see [audit burndown assignments](https://docs.google.com/spreadsheets/d/1d1oG67eoJWRKMBsYDNMT510_b9J0mPetxsL277k-Jtc/edit#gid=1289369769)

### Phase 6 - Transitional Compatibility Layer / Parity / DevTools compat

- [x] Add Fraggle Rock mode to CLI
    - [x] fraggle rock navigation mode
- [x] Test framework for additional cases
- [x] #12861
    - [x] set throttlingMethod devtools by default in timespans
    - [x] protocol timeout support on session
    - [x] preserve devtools log in error cases
    - [x] preserve trace in error cases (ask @paulirish if necessary)
    - [x] OOPIF support
    - [x] config parity
      - [x] navigation extension (via `id`)
      - [x] plugin support
      - [x] config validation
        - [x] warn and drop audits that don't have artifacts met
- [x] GatherContext as base artifact
- [x] driver.disconnect implementation
- [x] additional trace categories
- [x] timespan emulation
- [x] fix screenshot issue #12988 (not fixable)
- [x] better logging

### Phase 7 - Report UI + API Hardening

- [x] API for joining multiple reports
- [x] decide which faked artifacts/LHR properties make the final cut in snapshot/timespan (see #12614 )
- [x] Flow Report UI
    - [x] tagged template literal / JSX / preact helpers
    - [x] summary view
        - [x] category summary grid
    - [x] navigation view
    - [x] timespan report
    - [x] snapshot report
    - [x] help
    - [x] more improvements
      - [x] i18n / pluralize
      - [x] custom report labels (not "Timespan report 1")
- [x] test the bejesus out of it all
    - [x] test real world pages/cross origin navigations that might switch processes of main thread
    - [x] Sample page https://github.com/GoogleChrome/lighthouse/pull/12850#discussion_r688680644
    - [ ] ~i18n string check https://github.com/GoogleChrome/lighthouse/pull/13215#discussion_r730066237~ tracked elsewhere
- [x] documentation
    - [x] getting started guide / explainer

#### High Priority

- [x] DevTools implementation
- [x] navigate from an existing page without URL knowledge i.e. provide `navigate: () => myLink.click()` instead of a URL
    - [x] navigate without the about:blank jumps
    - [x] remove dependency on `requestedUrl` and/or backfill requestedUrl to match
- [x] Add Flow Report support to LH viewer + gist (high priority because it will assist with testing)
- [x] https://github.com/GoogleChrome/lighthouse/issues/13364

##### Epics

- [ ] ~single page app navigation mode (provide SPA load metrics like navigation, not just timespan)~ tracked elsewhere
- [ ] ~opportunity rework to focus on kilobytes rather than wastedMs~ primo prio
- [ ] ~anti-clobber mode (go through our methods that can stomp on puppeteer usage and optionally skip them)~ tracked elsewhere
    - [ ] ~throttling~
    - [ ] ~emulation~
    - [ ] ~blocked URL patterns~
    - [ ] ~request interception~
    - [ ] ~javascript dialogs~
    - [ ] ~disconnect should disable *all* settings~
- [ ] ~cleanup~ tracked elsewhere
    - [ ] ~remove legacy path~
        - [ ] ~remove gather-runner~
        - [ ] ~remove artifact hacks for~ 
    - [ ] ~update config helpers to use new FR types~
- [x] expand FLHR to include interaction steps, labels, etc
- ~[ ] More consistent thumbnails ([example](https://gist.github.com/brendankenny/9168bb5da157243e55b427230bfdc737))~

##### Tasks
Roughly priority ranked.

- [ ] ~ensure that defaultSession can't be used to enable/disable domains~ not doing
- [ ] ~enforce any use of `*.disable` must use a dedicated session~ not doing
- [ ] ~Highest-impact audits https://github.com/GoogleChrome/lighthouse/pull/13082~ tracked elsewhere
- [ ] ~artifact improvements~ not doing
    - [ ] ~split cssusage artifact into stylesheet content and usage~
    - [ ] ~split jsusage artifact into script content and usage~
- [ ] ~mobile viewport for flow report~ tracked elsewhere
- [ ] ~pagedependencygraph support for timespans~ fuck no

## CDP Asks

- getThrottlingSettings/getEmulationSettings

## Related Issues

#1769
https://github.com/GoogleChrome/lighthouse/issues/3837
https://github.com/GoogleChrome/lighthouse/issues/11312
#11122
https://github.com/GoogleChrome/lighthouse/issues/6028
https://github.com/GoogleChrome/lighthouse/issues/1418
https://github.com/GoogleChrome/lighthouse/issues/2332

**Comment by patrickhulce** [comment]
We've put together a [project plan and rough design doc](https://docs.google.com/document/d/1fRCh_NVK82YmIi1Zq8y73_p79d-FdnKsvaxMy0xIpNw/edit#) that's open for comments.

I've also updated this issue to reflect the early phases of the plan. 

**IMPORTANT**: This next phase starts to cement terminology like `timespan`, `snapshot`, and `navigation`. If you have alternative suggestions for these, please please speak up *now*.

**Comment by YaakovHatam** [comment]
There is a scenario where I have to run the lighthouse through the cli after I browse. Since lighthouse does not "take over" on an existing tab, I did the following hack:
In the file `lighthouse-core\gather\driver\navigation.js` (Which is located in global node_modules dir, for ex. `C:\Users\user\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\driver\navigation.js`)

i added the code 
```javascript
![lighthouse1](https://user-images.githubusercontent.com/6986221/142753548-7bd08368-14f1-451a-9a0d-98ab67b84130.PNG)
![lighthouse2](https://user-images.githubusercontent.com/6986221/142753551-6f0ef733-7b5f-4ec0-a397-f63e7800bde4.PNG)

const readline = require('readline');

function askQuestion(query) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise(resolve => rl.question(query, ans => {
    rl.close();
    resolve(ans);
  }))
}
```
after `'use sctrict'`

and, before the code
```javascript
if (options.debugNavigation) {
```
i added the code:
```javascript
 if (url != 'about:blank') {
    await askQuestion("Are we ready?");
  }
```

and now, i can navigate to page i want, and resume the cli with the checks.

attaching lighthouse1.PNG and lighthouse2.PNG to see it in action

**Comment by yorispakaimu11-ai** [comment]
Kacamata Anda sebagai seorang Profesional (khususnya sebagai seorang Insinyur
Profesional dan secara umum sebagai seorang Profesional Executives dan/atau
seorang Professional Entrepreneurs)!
                                     Kepemimpinan Profesional dan Inovasi Insinyur 2026

**Comment by yorispakaimu11-ai** [comment]
[Kepemimpinan Profesional dan Inovasi Insinyur 2026 .dot.doc](https://github.com/user-attachments/files/25622235/Kepemimpinan.Profesional.dan.Inovasi.Insinyur.2026.dot.doc)

**Comment by yorispakaimu11-ai** [comment]
[Studi_Kasus_Jaringan_Internet_Mappi_Lengkap_dengan_Gambar Y86.docx](https://github.com/user-attachments/files/25622237/Studi_Kasus_Jaringan_Internet_Mappi_Lengkap_dengan_Gambar.Y86.docx)
