### ISSUE TITLE
☂️ 👣 LH v8 burndown

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#11866]
A collection of breaking and non-breaking changes we'd like to make in LH v8. If you come across any API that would be nice to change, add it here :)

### metrics & perf
- [x] reweight metrics in perf score  · [PR #12577](https://github.com/GoogleChrome/lighthouse/pull/12577)
- [x] TBT realignment with field FID (go/wtsiw)  · [PR #12576](https://github.com/GoogleChrome/lighthouse/pull/12576)
- [x] replace CLS with NLS (partially nonbreaking) · #12350
  - [x] add allframes to new CLS  · [PR #12476](https://github.com/GoogleChrome/lighthouse/pull/12476)
  - [x] replace CLS with new version, remove old variants · [PR #12554](https://github.com/GoogleChrome/lighthouse/pull/12554)
  - [x] update PSI to m90 to support allframes
- [x] update FCP score curve · [PR #12556](https://github.com/GoogleChrome/lighthouse/pull/12556)

### release notes
- [x] Score changes summary/faq  · [PR #12597](https://github.com/GoogleChrome/lighthouse/pull/12597)
- [x] PSI/CRUX release notes

### i18n
- [x] fresh import · [PR #12591](https://github.com/GoogleChrome/lighthouse/pull/12591)

### breaking changes
- [x] rename uses-webp-images to `modern/nextgen-image-formats` (or something) · [PR #12535](https://github.com/GoogleChrome/lighthouse/pull/12535), [stack-packs#63](https://github.com/GoogleChrome/lighthouse-stack-packs/pull/63)
- [x] ImageElement artifact shape fixes (#12077) · [PR #12568](https://github.com/GoogleChrome/lighthouse/pull/12568)
- [x] remove firstCPUIdle? remove estimatedInputLatency?  · [PR #12553](https://github.com/GoogleChrome/lighthouse/pull/12553)
- [x] remove postMessage loading from treemap app  · [PR #12519](https://github.com/GoogleChrome/lighthouse/pull/12519)

### deps
- [x] drop `intl` polyfill · [PR #12426](https://github.com/GoogleChrome/lighthouse/pull/12426)
- [x] update chrome-launcher to 0.14.0 (node version change) · [PR #12507](https://github.com/GoogleChrome/lighthouse/pull/12507)
- [x] update axe-core to 4.2.1 · [PR #12575](https://github.com/GoogleChrome/lighthouse/pull/12575) ~~[PR #12536](https://github.com/GoogleChrome/lighthouse/pull/12536)~~

## Punted to v9

- possibly recalibrate throttling multipliers · #9085
- redirects performance consistency observed v. simulated  · #8984
- move to minimum Node 14
- drop `TagsBlockingFirstPaint` gatherer and base `render-blocking-resources` on `LinkElements` and `ScriptElements` instead · https://github.com/GoogleChrome/lighthouse/pull/11841#issuecomment-749136678?  probably pending decision on  AMP special handling

**Comment by brendankenny** [comment]
Time for #12614!
