### ISSUE TITLE
☂️ Breaking changes for v9

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#12614]
- [ ] https://github.com/GoogleChrome/lighthouse/issues?q=label%3A9.0+
- [x] Remove `redirects-http` #12643
- [x] Remove `appcache` - as of m95, appcache is gone. no more OT that kept it alive. #13287
- [x] Remove preload audits based on #11960 (likely needs more investigation based on pmeenan's recent preload improvements - one option is to remove from default config for v9 (rather than keep as N/A that just sit there)).
- [x] Remove `mimeType` from `ImageElements` gatherer https://github.com/GoogleChrome/lighthouse/pull/13265
- [x] remove `url` prop in `errors-in-console` details #13286
- [x] Remove PWA category gauge function alias https://github.com/GoogleChrome/lighthouse/pull/13269
- [x] visual indicator of mobile/desktop on perf score - #8178
- [ ] report api #12772  

### Punted from v8

- [x] move to minimum Node 14 · #13243

Previously: [v8.0 burndown](https://github.com/GoogleChrome/lighthouse/issues/11866)

------

Punting

- [ ] possibly recalibrate throttling multipliers · #9085
- [ ] redirects performance consistency observed v. simulated  · #8984
- [ ] Require `supportedModes` in audits https://github.com/GoogleChrome/lighthouse/pull/12649
- [ ] Mark `BenchmarkIndex` optional, remove in snapshot mode / repeated flow situations (we lost context for motivation for this. seems ok but not important)
- [ ] drop `TagsBlockingFirstPaint` gatherer and base `render-blocking-resources` on `LinkElements` and `ScriptElements` instead · https://github.com/GoogleChrome/lighthouse/pull/11841#issuecomment-749136678?  probably pending decision on  AMP special handling. 
   - Also perhaps instead: we use the render-blocking signal from trace events (TODO find issue)

**Comment by lifeart** [comment]
Note for:
 * possibly recalibrate throttling multipliers · #9085

Modern CPU's has different perf-boost techniques, like TurboBoost, and it may temporary improve performance up to 30+%, and "second" measurement can catch performance decrease, because of "cooling" CPU policy.

Also, performance may be different, depends on selected power plan (Windows)

**Comment by connorjclark** [comment]
Last 8.x release is ~Oct 12
