### ISSUE TITLE
☂️ Convert to ES modules

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#12689]
Not breaking changes:

- [x] Report renderer
- #12623
- #12690
- #12702
- [x] Viewer #12878
- [x] Treemap #12892
- [x] Extension (this code is isolated and never touched so we could skip/defer until next change) #14181
- [x] Client entries (CDT and LR) #13722
- [x] CLI #13045
- [x] Collect strings (support collecting from ES modules) #12741
- [x] Scripts #13121
- [x] Tests #13046
- [x] Lighthouse Logger #13720
- [x] Build #13967 

Breaking changes, wait for v10:

- [ ] Core
  - [x] Tests #13295
  - [x] `locales.js`: use `fs.readFileSync` or change locales to `.js` files #12721
  - [x] #13974
  - [ ] ... more sub tasks ... (TODO: work this out)

[doc](https://docs.google.com/document/d/1E0dwjbItFFXLJk3TjFr1dHbXLqkPuTwVrhwvbbigp4I/edit?usp=sharing&resourcekey=0-oDI_CvqEo3QjX7r0ca3hMA)
(below is just some repeated info)
________

## Changing CLI to esmodules isn't breaking?

Nope–the interface for the CLI is via the command line, not programmatic.

## How to breakup work?

Reminder: ES modules can import commonjs, but the inverse is not possible (not without doing async imports). Therefore chunks of code with no dependents should be converted first.

Scripts and tests use modules from everywhere, so those should be converted first.

The report renderer, viewer, treemap, extension, CLI, scripts and tests can all be done independently, one at a time as they have no dependents (also mostly true for individual tests and scripts, but the dependency chains there are small).

Core is a big beast, and has the hardest problems to work out (I'm thinking of the config dynamic module loading code). The CLI depends on Core, so CLI must be converted first. Once `lighthouse-core/runner.js` and `lighthouse-core/index.js` is converted, and the config module loading is worked out, should be able to do each folder in `lighthouse-core` individually (but at this point, with everything else done, it may be reasonable to do all of it at once). See https://gist.github.com/connorjclark/22105a01b471811d9c5ccf989db3059d for part of the dependency list (doesn't include any dynamic modules).

The `package.json` `type` field is what enables esmodules (we don't want to do `.mjs`), and luckily the nearest `package.json` file is used, so during the transition we can just write `{type: "module"}` files where necessary.

## Lighthouse Logger

This will be cumbersome since it is its own package. Should we move this into Lighthouse proper as `lighthouse-core/lib/logger`? We could defer updating the npm package until necessary, and drop the dependency on `lighthouse-logger`; that should allow us to convert this code w/o a breaking change.

EDIT: turns out this is simpler than all that. see #13720

## Read more

https://electerious.medium.com/from-commonjs-to-es-modules-how-to-modernize-your-node-js-app-ad8cdd4fb662

**Comment by brendankenny** [comment]
https://github.com/facebook/jest/issues/10025 ("jest.mock does not mock an ES module without Babel") seems like it will likely be an issue for us on the testing side. A draft PR is up to fix it (https://github.com/facebook/jest/pull/10976), but has been open for seven months and doesn't look to be a priority for them right now.

**Comment by connorjclark** [comment]
esm-core branch unit test segfaults atm: https://github.com/GoogleChrome/lighthouse/runs/6461306971?check_suite_focus=true#step:13:1378

May be node vm dynamic import [crbug](https://github.com/nodejs/node/issues/35889), but also could be c8?

note: there is a non-segfaulty v8 bug too (`Test environment has been torn down`) but that is handled with this fancy script: https://github.com/GoogleChrome/lighthouse/blob/23b4add7bb59f1fbaad2c3d0c7278b78c6e01616/lighthouse-core/scripts/run-jest.sh#L19

**Comment by connorjclark** [comment]
I'd say this is pretty much all done!
