### ISSUE TITLE
Fraggle Rock Smoketest Parity with Legacy

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#12861]
We have a number of failure groups for various reasons, some expected, others not so much. Using a separate issue to track these parity issues more closely than #11313 

- pwa (expected, we have planned non-support for http-redirect, fewer passes means fewer requests to server)
- offline (expected, we have planned non-support for http-redirect, fewer passes means fewer requests to server)
- [x] Stacks artifact is sometimes empty #12907
- [x] Number of 404 requests is different on `dbw` #12907 
- [x] TTI quiet window can't be found on `redirects-single-server` / `metrics` #12873
- [x] non-200 status does not produce a report on `seo-status-403` #12862
- [x] viewport is different on `seo-tap-targets` #12907
- [x] infinite loop hangs LH on `errors-infinite-loop` #12913 
- [x] screenshot node IDs changed #12912
- [x] oopif support #12992 

When this is complete, expected `--invert-match pwa offline`

**Comment by patrickhulce** [comment]
All work here is complete and parity on all smokes that aren't slated for removal has been reached 🎉
