### ISSUE TITLE
Gather/Audit Mode in User Flows

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#13364]
The `-G` and `-A` flags can be used to run the gathering and auditing phases separately in the CLI. We should add some way to run these phases separately in user flows.

Previous discussion: #11623

## Benefits of 2-stage User Flows
- <ins>Faster audit workflow</ins>: User flows can take arbitrarily long. Would be nice to test audit changes in flows using existing artifacts without running an entire user flow.
- <ins>Deterministic sample updating</ins>: (TL;DR `sample_v2.json` for user flows) To rebaseline the sample flow report, we currently run an end-to-end user flow experience. This means normal page variance tends to bloat the size of the sample diff, making reviews of sample diffs hard and CI verification impossible. Separate gathering modes allow us to check-in an artifacts file and test how changes to the auditing phase affect the final flow result deterministically.
- <ins>Less stalling in the middle of a flow</ins>: We could defer auditing for each step to the end of the entire flow. Small impact compared to running gatherers, but should come for free with these changes.

## Implementation Plan

- [x] Create helper to handle gather phase https://github.com/GoogleChrome/lighthouse/pull/13519
	- `gatherArtifactsOrLoadFromFile()` or something
		- Thinking about making this a static function on `Runner` but open to suggestions here.
	- ~We won't handle the `-G` logic for user flows, but it's important that individual navigations respond to the `-G` flag to maintain parity when running Lighthouse CLI with the `--fraggle-rock` flag.~
- [x] Remove gathering phase from `Runner.run()` https://github.com/GoogleChrome/lighthouse/pull/13569
	- Current interface: https://github.com/GoogleChrome/lighthouse/blob/68ba77acbc9c22512b93d213b23b05cca443dda4/lighthouse-core/runner.js#L30-L36
	- Proposed interface:
	  
      ```js
	    /**
	     * @template {LH.Config.Config | LH.Config.FRConfig} TConfig
	     * @param {LH.Artifacts} artifacts
	     * @param {{config: TConfig, ...}} runOpts
	     * @return {Promise<LH.RunnerResult|undefined>}
	     */
	    static async run(artifacts, runOpts) {
	  ```
    - Effectively turns `Runner.run()` into and "audit runner".
	- Call to function from step 1 lifted to `lighthouse-core/run.js` and ~navigation runner~ all FR runners. Results are passed to `Runner.run()`.
	- ~Timespan and snapshot runners would directly run whatever is in their `gatherFn` and pass results as a param to `Runner`~.
	- https://github.com/GoogleChrome/lighthouse/pull/12393

- [x] Move FR usage of `Runner.run` to `user-flow.js` and `api.js` https://github.com/GoogleChrome/lighthouse/pull/13623
	  - Individual FR runners `snapshot`, `startTimespan`, `navigation` will return artifacts instead of a `RunnerResult`.
	  - Add wrapper functions that send returned artifacts through `Runner.run()` in `api.js`. Maintains the current API for individual runners.
	  - Artifacts will be saved on an instance of `UserFlow`. Auditing can be run as part of `UserFlow.getFlowResult`.
- [x] Add `saveArtifacts` and `loadArtifacts` functions to `UserFlow`
  	  - Pass artifacts into the constructor?
- [x] Update sample flow JSON script runs audit mode on some checked-in artifacts.
- [ ] Add CI check for sample flow JSON

**Comment by brendankenny** [comment]
@adamraine I think a lot of this is aligned with the RFC/discussion in #12393 as well

**Comment by adamraine** [comment]
Ah yeah forgot https://github.com/GoogleChrome/lighthouse/pull/12393. It should cover step 2.
