### ISSUE TITLE
Distinguish Navigation URLs and Frame URLs

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#13706]
## Terminology

This doesn't have to stick, I just need it to make writing the issue easier.

- **Navigated (Navigation?, Document?) URL**: The the last URL the browser performed a hard navigation to.
	- Lighthouse resolves this URL tracking CDP `Page.frameNavigated` events.
	- Can only be determined in Lighthouse if there was a navigation
- **Frame URL**: The URL that appears in the search bar. Can be changed with `history.pushState` or anchor links without making an additional network request or performing a hard navigation.
	- Lighthouse legacy navigation runner does not use this URL anywhere.
	- URL can queried using `Page.getFrameTree`.
	- Lighthouse FR runners can resolve this URL using the Puppeteer `page.url()` function ([wrapped by `driver.url()`](https://github.com/GoogleChrome/lighthouse/blob/9addbda51d4121c6a8d650c42cee11ce0876d66a/lighthouse-core/fraggle-rock/gather/driver.js#L65-L67)).

## Problem

For navigations, gatherers need to know the navigated URL in order to find the main document, and there can be issues if the frame URL is provided instead. #13699 will ensure consistent use of the navigation URL for navigation mode. However, timespan and snapshot mode cannot resolve the navigated URL without `Page.frameNavigated` events, so [they must use the frame url with `page.url()` instead](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/fraggle-rock/gather/timespan-runner.js#L35).

In the LHR `requestedUrl`/`finalUrl`, we use the nav URL which can be confusing to the end user who probably expects the frame URL https://github.com/GoogleChrome/lighthouse/issues/13697. Again, this does not apply timespan/snapshot which have to use the frame URL everywhere.

Once #13699 is merged the following shows when each "type" of URL will be returned from different sources:

| | Gather `context.url` | `artifacts.URL` | `lhr.requestedUrl` / `lhr.finalUrl` | `driver.url()` / `page.url()` |
| - | - | - | - | - |
| _Legacy_ | Navigation URL | Navigation URL |  Navigation URL |  N/A |
| _Navigation_ | Navigation URL | Navigation URL |  Navigation URL |  Frame URL |
| _Timespan_ | Frame URL | Frame URL | Frame URL | Frame URL |
| _Snapshot_ | Frame URL | Frame URL | Frame URL | Frame URL |

## Solution

To ensure the "type" of URL is consistant in all three modes, I propose the following setup:

| | Gather `context.url` | `artifacts.URL.*` | `lhr.requestedUrl` | `lhr.finalUrl` | `driver.url()` / `page.url()` |
| - | - | - | - | - | - |
| _Legacy_ | Deprecated | See below |  Navigation URL |  Frame URL | N/A |
| _Navigation_ | Deprecated | See below |  Navigation URL |  Frame URL | Frame URL |
| _Timespan_ | Deprecated | See below | N/A | Frame URL | Frame URL |
| _Snapshot_ | Deprecated | See below | N/A | Frame URL | Frame URL |

New `URL` artifact:
```ts
interface URL {
	/** URL of the main frame before Lighthouse starts */
	initialUrl: string;
	/** URL of the first document request during a Lighthouse navigation. `undefined` in timespan/snapshot modes. */
	requestedUrl?: string;
	/** URL of the last document request during a Lighthouse navigation. `undefined` in timespan/snapshot modes. */
	mainDocumentUrl?: string;
	/** URL of the main frame after Lighthouse finishes */
	finalUrl: string;
}
```

Some notes on the above proposal:
- Gather `context.url` is deprecate because we can get the Nav URL from `artifacts.URL` and the frame URL from `driver.url()`
- `lhr.requestedUrl` will be an optional property that only appears on navigation LHRs.
- Add new `initialUrl` to be a staple of every `artifacts.URL`
	- Frame URL
	- Would be `about:blank` on most navigations.

## Implementation Plan

- [x] Add `initialUrl` and `mainDocumentUrl` to the `artifacts.URL`.
- [x] Switch audit/computed artifact usages of `artifacts.URL.finalUrl` to `artifacts.URL.mainDocumentUrl`
- [x] [Possibly breaking?] Deprecate `context.url`
- [x] [Breaking] Make `requestedUrl` undefined in timespan/snapshot on `artifacts.URL` and the LHR
- [ ] [Breaking] Add `finalDisplayedUrl` and deprecate `finalUrl`
- [ ] Add `mainDocumentUrl` to the LHR
- [ ] Remove `initialUrl` and hold until we actually need it

## Related
https://github.com/GoogleChrome/lighthouse/issues/8984

**Comment by adamraine** [comment]
Interesting development, I think we can use [`Page.getNavigationHistory`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getNavigationHistory) to resolve the `mainDocumentUrl` in timespan and snapshot mode. This means `mainDocumentUrl` doesn't ever need to be undefined.

**Comment by adamraine** [comment]
From our discussions in https://github.com/GoogleChrome/lighthouse/pull/13819, it seems like we have 3 bikeshedding decisions to make:
1. Do we keep `finalUrl` on the LHR as the final navigation URL? This will be purely for legacy support, our own clients should never use this.
2. What do we call the final navigation URL? This issue originally proposed `mainDocumentUrl`, other ideas proposed:
	- `mainResourceUrl`
	- `finalNavigationUrl`
	- `finalNavigatedUrl`
	- `finalNetworkUrl`
3. What do we call the final frame URL? This issue originally proposed using `finalUrl`, I don't think anyone wants this anymore. Other ideas proposed:
	- `finalFrameUrl`
	- `displayedUrl`
	- `finalDisplayUrl`
	- `finalDisplayedUrl`

I'm not including `finalDocumentUrl` because @connorjclark [proposed it for the final frame URL](https://github.com/GoogleChrome/lighthouse/pull/13819#issuecomment-1154500144) and @brendankenny [proposed it for the final document URL](https://github.com/GoogleChrome/lighthouse/pull/13819#issuecomment-1155675175) (lol). Clearly that name is confusing.

My preferences:
1: Keep `finalUrl` on the LHR only for legacy support
2: `mainDocumentUrl` because that's what we have right now
3: `finalDisplayedUrl`

**Comment by paulirish** [comment]
> I'm not including `finalDocumentUrl` because @connorjclark [proposed it for the final frame URL](https://github.com/GoogleChrome/lighthouse/pull/13819#issuecomment-1154500144) and @brendankenny [proposed it for the final document URL](https://github.com/GoogleChrome/lighthouse/pull/13819#issuecomment-1155675175) (lol). Clearly that name is confusing.

brendan also pitched "navigated"/"navigation" for the `finalUrl`/`finalNetworkUrl` concept. IMO this doesnt work since the [navigation API](https://wicg.github.io/navigation-api/#global-navigate) changes the URL but not this one.
