### ISSUE TITLE
CI is red

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#13847]
- [x] new installability error: fix in #13846 @adamraine 
- [x] `yarn smoke --runner devtools oopif-scripts`: disabled in #13859 @connorjclark
- [x] `yarn smoke redirects-client-paint-server` in ToT/Canary: fix in #13848 @adamraine 
   not currently running in CI, but running (and failing) once #13844 fixes the shard count

**Comment by adamraine** [comment]
> yarn smoke redirects-client-paint-server

I filed a bug related to the speed index failures in this one
https://bugs.chromium.org/p/chromium/issues/detail?id=1309154&q=reporter%3Ame&can=2. Looks like it's expanded to include violations in other metrics as well.

**Comment by connorjclark** [comment]
re: `oopif-scripts` isPositionFixed flakiness (which I think only happens locally?)

<img width="827" alt="image" src="https://user-images.githubusercontent.com/4071474/163443922-758bd729-9077-4512-9399-f0e8900545ea.png">

We consider it not fixed if there is no Y overflow...

Not sure how this ever passes, because when I go to the page manually the console always shows `htmlEl.scrollHeight === htmlEl.clientHeight`

**Comment by brendankenny** [comment]
Yeah, this fails locally for me even going back to the commit where it landed (ceb03cb247125f7b594cd419bb8db953bd77fbc3) and using Chrome 99/100. This one is a mystery.

Luckily it's not a very old test. Do you still have enough context to revise it? e.g. was `isPositionFixed: true` important, and if so, could the layout be adjusted to make it pass again?

**Comment by connorjclark** [comment]
Yeah we could just force the html element to be taller than the viewport. I'll try that.
