### ISSUE TITLE
Audits: Detect byte and time savings from bundled resources

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1517]
Across the byte efficiency audits time saved from data URI resources, stylesheets added from script is not accurately reflected. Ideally we'd be able to attribute these resources to the actual network record they come in on (the JavaScript or HTML file that included them), but at a minimum we can estimate the network throughput and time saved on average.

- [ ] Attribute inline CSS stylesheets to the appropriate HTML or JS file - https://github.com/GoogleChrome/lighthouse/issues/1544
- [X] ~Provide a byte estimate for inline stylesheets #1536~
- [X] ~Provide a time estimate for inline stylesheets #1536~
- [X] ~Attribute data URI images to the appropriate HTML/JS/CSS file~ no longer needed
- [X] ~Provide a time estimate for data URI images #1536~

**Comment by ebidel** [comment]
I've been thinking it would be really nice to work towards very visual infographic-type callouts in the report. High level aggregations, but also breakdowns as you drill into each of these audits. Something like:
https://pageweight.imgix.com/jobs/99166054-29d7-413a-a0c4-1d7c8e30a8e2.html?utm_source=share-link

I'm visual. Users are visual. The world loves visuals!

**Comment by brendankenny** [comment]
see also [May 2016 UX mocks](https://docs.google.com/document/d/1ZEPbE79DmMXLyUQ3k8pxQVQaiWxcg4wCDfLlwy3BZaE/edit). There are various Irish/Lewis mocks spread out in issues as well (cc @paulirish)

(no pie charts, tho :P)

**Comment by patrickhulce** [comment]
#1500 is related to first bullet on attribution of inline stylesheets

**Comment by patrickhulce** [comment]
Marking this as closed since the last remaining enhancement is now orthogonal to the original intent of the issue and is tracked separately in #1544.
