### ISSUE TITLE
Rename meta viewport audit

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/lighthouse#16020]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://resource-loading.glitch.me/meta-viewport.html

### What happened?

It reports this:
> Does not have a <meta name="viewport"> tag with width or initial-scale

But it DOES have a `<meta name="viewport">` tag with width and initial-scale.
We changed this in #15394

We should rename this audit to:
> Does not have a <meta name="viewport"> tag with width and initial-scale >= 1

### What did you expect?

It to tell me the problem, not confuses me.

See also: https://stackoverflow.com/questions/78536947/pagespeed-problem-with-initial-scale-does-not-have-a-meta-name-viewport

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

12.0.0.0

**Comment by adamraine** [comment]
@tunetheweb how do you feel about "Has a mobile optimized viewport" which better reflects the goal of this audit?

**Comment by tunetheweb** [comment]
SGTM!

**Comment by connorjclark** [comment]
done (but for the new insight audit).
