### ISSUE TITLE
Meta charset not defined

### ISSUE THREAD

**Issue by AdrianoLMRS** [GoogleChrome/lighthouse#16289]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://pousada-tao.onrender.com/

#### Properly defines charset - Error!
<br>
<details><summary>Error description</summary>

> A character encoding declaration is required. It can be done with a <meta> tag in the first 1024 bytes of the HTML or in the Content-Type HTTP response header. [Learn more about declaring the character encoding](https://developer.chrome.com/docs/lighthouse/best-practices/charset/?utm_source=lighthouse&utm_medium=lr).

</details>

My charset is correctly defined in my HTML head (it is the first meta tag), but this annoying error keeps happening... <br>
<details><summary>Full HTML tag</summary>
<br>

```
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pousada TAO Campos do Jordão</title>
    <link rel="icon" type="image/x-icon" href="https://res.cloudinary.com/dycnoic1s/image/upload/v1734371342/elemento_flor.fw_2_wr5wtf-fpng_1_whto4n.png">
<!-- ...css styles -->
</head>
<!-- ...</body> tag -->
```
<br>

</details>

-  Full code: [My index.html (github repo)](https://github.com/AdrianoLMRS/Pousada-TAO/blob/main/app/public/index.html)
<br>
There are these related issues that I already looked:

- [Warn about late, or missing, <meta charset> #15498]( #15498)

- [Self closing <meta charset> isn't detected #11956]( #11956)

### What did you expect?

**Not getting this error ):**

### What have you tried?

1. Using a node middleware to set content type to always = _content-type: text/html; charset=UTF-8_ 

2. Using curl with WSL to verify the charset `curl -I https://pousada-tao.onrender.com/` <br> Output = `HTTP/2 200 date: Tue, 17 Dec 2024 22:49:32 GMT content-type: text/html; charset=UTF-8`

3. Trying in several browsers :
-  Chrome v131.0.6778.140 
- Firefox v134.0b10
- Brave

4. Setting up the html with github pages (Same error occurs)

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools, Other

### Lighthouse Version

v100.0.0.3 (extension)

### Chrome Version

v131.0.6778.140

### Node Version

v18.19.1

### OS

Windows (WSL)

### Relevant log output

```sh
curl -I https://pousada-tao.onrender.com/
# Output :
HTTP/2 200
date: Tue, 17 Dec 2024 22:49:32 GMT
content-type: text/html; charset=UTF-8
cf-ray: 8f3a7787bed79ca6-GIG
cf-cache-status: DYNAMIC
cache-control: public, max-age=0
etag: W/"a968-193d6cb1e00"
last-modified: Tue, 17 Dec 2024 22:44:16 GMT
vary: Origin, Accept-Encoding
access-control-allow-credentials: true
rndr-id: cbeb2cb7-913c-458a
x-powered-by: Express
x-render-origin-server: Render
server: cloudflare
alt-svc: h3=":443"; ma=86400
```

**Comment by AdrianoLMRS** [comment]
I also have tried these websites :
- [GTmetrix](https://gtmetrix.com/)
- [Webpagetest](https://www.webpagetest.org/)
- [Pingdom](https://tools.pingdom.com/)
- [w3htmlValidator](https://validator.w3.org/nu/#textarea)

And I didn't get the same error ...

**Comment by adamraine** [comment]
I can repro, this is caused by a second cancelled document request initiated during the page load. When we try and get the main document we should filter out any failed/cancelled requests.

**Comment by connorjclark** [comment]
fixed in https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/6112617
