### ISSUE TITLE
WPT compat: play nicely with video recording

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1730]
WPT already records the video of Lighthouse working its magic but a couple of things need to be done on our side to make processing possible since we're mostly a blackbox.

- [x] ~Support custom blank pages per pass through config~ (#1732)
- [x] ~Support custom blank page hold durations per pass through config~ (#1732)
- [x] ~Support config extensions~ (#1731)
