### ISSUE TITLE
[meta] V2 Report Burndown

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1887]
_This list will be updated_

### Overview
* [ ] Add config v2 MVP #1880 [@patrickhulce]
* [ ] Add `--v2` flag. [@brendankenny]

### Report sprint
* [ ] Add report DOM renderer MVP [@dgozman]
  * [ ] Re-sort topics by failures [@robdodson]
  * [ ] Hide passing audits [@ebidel]
  * [ ] Render Markdown to DOM [@brendankenny]
  * [ ] Migrating various formatters to DOM [team]

### Audit IA refactor
* [ ] Perf metrics move [@patrickhulce]
* [ ] PWA topics collapse into audits [@paulirish]

### PWA definition - Align PWA items w/ Checklist  [@ebidel]
* [x] add TTI < 10s audit [@paulirish]
* [ ] Add placeholders for crossbrowser, etc
* [ ] Express PWA boolean along with score (decide how score and boolean relate)

**Comment by wardpeet** [comment]
if it helps I can make the report cross browser ^^

**Comment by ebidel** [comment]
@paulirish since we can test the additional PWA checklist items, do we need fake audits for them (crossbrowser, each page has an url, page transitions dont fee janky)? There's already a note at the top of the section that says our items are a subset of the checklist and links to it:

<img width="667" alt="screen shot 2017-03-22 at 4 51 21 pm" src="https://cloud.githubusercontent.com/assets/238208/24225838/ef04af5e-0f1f-11e7-86c5-c388a9313a48.png">

**Comment by paulirish** [comment]
@ebidel not sure! we could do fake audits (a la comingSoon) or some paragraph text at the end of the section, or something else. The paragraph text doesn't sound so bad to me.

For expressing the PWA boolean I think we should plan on showing like a green checkmark if you're good.  So maybe something like

> ### Congrats, you're bonafide! 
> #### You've met the requirements for a [baseline progressive web app]()*.

> *Baseline PWAs require a few criteria that Lighthouse didn't test. 1) The site must work crossbrowser. 2) Each page must have a URL. 3) Transitions between pages dont feel janky. [Read more here]().

Just spitballing, so whatever. :)

**Comment by paulirish** [comment]
closing in favor of the io burndown issue. #1937 

i filed the new #2059 to capture our convo here about the untested PWA reqs
