### ISSUE TITLE
[meta] I/O Burndown

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1937]
_Feel free to comment or edit. Check items once PRs are up for review, rather than when merged._

---------

### Report and Config refactors
* [x] ReportinDOM: Render the Lighthouse report without innerHTML [team]
  * [x] Refactor from Handlebars -> DOM (#1933) _#blocksDevTools_  [@dgozman]
  * [x] No more markdown links [@ebidel]
  * [ ] Remove markdown from descriptions. [?]
  * [ ] Migrate formatters to DOM [@ebidel, others]
    * [x] cards https://github.com/GoogleChrome/lighthouse/pull/1992
    * [x] table [@paulirish]
    * [ ] critical request chain [@ebidel]
    * [ ] nodes incl revealing (a11y) [@paulirish]
    * [ ] user timings [?]
    * [ ] url list [@patrickhulce]
  * [x] show [passing tests UI](https://docs.google.com/document/u/1/d/1jFoI5Anwm033n7SDabqUbjiWMzY2X31n5CqP254RH3A/edit#) [@paulirish]
  * [x] [performance UI](https://docs.google.com/document/u/1/d/1jFoI5Anwm033n7SDabqUbjiWMzY2X31n5CqP254RH3A/edit) for filmstrip & metrics ([crbug.com/717082](https://bugs.chromium.org/p/chromium/issues/detail?id=717082)) [?]
  * [x] perf diagnostics: sparklines of estimated cost (#2112) [@patrickhulce]
  * [ ] ~~Report UI: view system (#2111, [crbug.com/717079](https://bugs.chromium.org/p/chromium/issues/detail?id=717079))~~ punt
  * [x] Report UI: gauge scores
  * [ ] Report UI: other misc report needs
* [x] DevTools UI: Sidebar ([crbug.com/717076](https://bugs.chromium.org/p/chromium/issues/detail?id=717076)) [@pavelfeldman]
* [x] DevTools UI: modal for starting new audit. ([crbug.com/717072](https://bugs.chromium.org/p/chromium/issues/detail?id=717072)) [@pavelfeldman]
* [ ] DevTools UI: share/context menu. print?  --- _may be punted_
* [x] Configv2: Aggregations -> Categories (#1935) [@patrickhulce]
* [x] Configv2: Subitems -> Tags (topics) [@patrickhulce]
* [x] Configv2: category/audit whitelisting via settings (#1988)  [@patrickhulce]

### Features & Improvements
* [ ] Audits: PWA section alignment (placeholders, HTTPS, and retitling) [@ebidel]
* [ ] Audits: Express PWA boolean (and choose relationship to score) [@brendankenny] - https://github.com/GoogleChrome/lighthouse/pull/2032
* [x] Audits: PWA collapsed 3 audits (#1847) [@paulirish]
* [x] Audits: Move perf metrics (#1876) [@patrickhulce]
* [x] Audits: Add new start_url is available via SW for webapp-install-banner (#1903) [@wardpeet]
* [x] Audits: Implement deep's TTI for comparison (#1800) _#blocksWPT_ [@patrickhulce]
* [x] Better video capture for WPT _#blocksWPT_ [@patrickhulce]
* [x] LighthousePlots: Run result collection & analysis [@wwwillchen + @patrickhulce]
  * [x] Process for local bulk runs, collection, and graphing (#1936) [@wwwillchen]
* [x] Metrics: Quantify screenshot failures _#blocksWPT_ [@patrickhulce]
* [ ] Metrics: Measure and improve metrics reliability _#blocksDevTools_ _#blockedByLHPlots_ [@wwwillchen]
  * [ ] Network throttling consistency & comparison to WPT/tsproxy shaping
  * [ ] Quantify Device differences -> CPU throttling calibration
  * [ ] _(Stretch)_ Quantify metrics variance (in good conditions)
* [x] CI story: Ship docs & recipes for webhook & issue status.  [@ebidel]
* [ ] Recipes: Revised Custom Gather & Audit recipe [@brendankenny]

## 🌆  ☑️  Nice to have for I/O 
* [x] Land audit: Compression gzip/br (#1513) [@paulirish]
* [x] New audit: Reduce server response time [@wardpeet]
* [ ] New audit: Avoid document redirects [@wardpeet]
* [x] New audit: Evaluate other TTI implementations [@patrickhulce]
* [ ] Dev ergonomics: Separate gather & audit into two phases (#1806) [@brendankenny]
* [x] Code health: Get Closure compilation for reportv2 and various typefixes [@brendankenny]
* [x] Configv2: Migrate --perf to Configv2 [@patrickhulce]
* [ ] Reduce bug count to 150
* [ ] Get caseq working to make screenshots reliable
* [ ] Get pavel to implement mutationeventlisteners as Violations
* [ ] File bug asking about javascript dialogs to figure it out. headless/xvfv? [@brendankenny]
* [ ] Operation Yaquina Bay items
* [ ] Reduce LHR size

## 🏈  🏖 Punt till after I/O 
* Additional audits e.g. CSS & JS Coverage
* Report: incremental/progress updates
* Dedicated LH-on-WPT landing page. Do after incremental.
* Config v2: strong support for `extends`
* Config v2: remaining config arch cleanup
* Report: other visual updates - tabs, nice expando sections
* Plots: `export`/`submit` flag to upload result/trace/artifacts to the cloud [@wwwillchen]
* Plots: Docs/scripts for pulling cloud results/traces down for local analysis

**Comment by paulirish** [comment]
closing in favor of https://github.com/GoogleChrome/lighthouse/issues/2161
