### ISSUE TITLE
[meta] I/O The Final Countdown

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2161]
_Picking up from #1937. Being updated as we go_

### Report UI
  * [x] Remove markdown from descriptions. [@patrickhulce]
  * [x] render: critical request chain [@ebidel]
  * [x] render: nodes incl revealing (a11y) [@paulirish, @patrickhulce], details for non-devtools [?]
  * [x] render: filmstrip #2239 [@patrickhulce]
  * [x] render: metrics timeline [@patrickhulce]
  * [x] render: user timings #2240  [@patrickhulce]
  * [x] render: url list [@patrickhulce]
  * [x] Perf category style (#2140)

### Improvements
* [x] Audits: PWA section alignment (add "comingsoon" placeholders for Crossbrowser, skeleton screens & the other one) [@brendankenny] - add 3 audits. helptext marked as informative.
* [ ] Audits: Express PWA boolean (and choose relationship to score) [@brendankenny] - https://github.com/GoogleChrome/lighthouse/pull/2032
* [x] CI story: Ship docs & recipes for webhook & issue status.  [@ebidel]
* [x] Recipes: Revised Custom Gather & Audit recipe [@brendankenny]
* [x] Audits: Merge start_url SW PR (#1903) [?]
* [ ] PWA fast enough: Update text about metric #2189

#### [Operation Yaquina Bay](https://github.com/GoogleChrome/lighthouse/issues/2146)
* [x] Don't disable cache, just clear it (#2156)
* [x] Merge dbwPass into defaultPass (#2160) [@patrickhulce]
* [x] Enable request blocking (of CSS) for redirectPass [@patrickhulce] (#2168)
* [x] Audits: continue to exclude fancy stuff audits for now (rough perf story)
* [x] binary search for speedline [@patrickhulce] (https://github.com/pmdartus/speedline/pull/49)
* [x] Disable styles gatherer (#2153) [@patrickhulce]
* [x] Disable image-optimization for cross-origin images (#2154) [@patrickhulce]

#### Other perf & devtools issues
* [ ] TracingAlreadyStarted bug - get repro to provide to caseq, perhaps disconnect during trace retreival?
  * [ ] Let's always "Tracing.stop()" at the beginning.
* [ ] Protocol method to Force non-background mode? [crbug.com/721832](https://bugs.chromium.org/p/chromium/issues/detail?id=721832)
* [x] File bug asking about javascript dialogs to figure it out. headless/xvfv? [@brendankenny]
* [ ] PerfReport: Network throttling consistency & comparison to WPT/etc shaping
* [ ] PerfReport: Quantify Device differences -> CPU throttling calibration

### Release mgmt
* [x] Ship lighthouse canary: node module / CLI
* [x] Ship lighthouse canary: extension
* [x] Ship new audits panel - [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=717085)

## 🌆  ☑️  Nice to have for I/O 
* [ ] DevTools: view trace
* [x] Audit: Merge ward's TTFB audit  [?]

## 🏈  🏖  Probably punted
* [ ] DevTools UI: share/context menu. print?  --- _may be punted_
* [ ] Affirm LHR shape as backwards-compatible return value. (maybe LHR)
  * We will need compatibility layer for importing old json.

## 🏈  🏖  Definitely punted
  *  ~~Report UI: view system (#2111, [crbug.com/717079](https://bugs.chromium.org/p/chromium/issues/detail?id=717079))~~ 
* Additional audits e.g. CSS & JS Coverage
* Report: incremental/progress updates
* Dedicated LH-on-WPT landing page. Do after incremental.
* Config v2: strong support for `extends`
* Config v2: remaining config arch cleanup
* Report: other visual updates - tabs, nice expando sections
* Plots: `export`/`submit` flag to upload result/trace/artifacts to the cloud [@wwwillchen]
* Plots: Docs/scripts for pulling cloud results/traces down for local analysis
* Audit:PWA alignment: HTTPS merge (redirect + host), and retitling [@ebidel]
* Remove traceviewer (#2235)
* [ ] Request caseq to help with making screenshots reliable
* [ ] Report overview (aka all failed audits)
* [ ] Reduce bug count to 150
* [ ] Dev ergonomics: Separate gather & audit into two phases (#1806) []
* [ ] New audit: Avoid document redirects [@wardpeet]
* [ ] implement mutationeventlisteners as Violations (#2163) [pavel]

**Comment by paulirish** [comment]
**To simplify, we'll be using the "rls blocker" label going forward for 2.0.** 

------------

This issue is fullllll of checked checkboxes.   OH YEAH. I'm closing it.

Everything up to the "Punted" sections is either done (yay!) or filed and tagged with "rls blocker".

There's still valuable stuff in punted section that may not be filed as tickets, but [I'll do a triage of them after I/O](https://github.com/GoogleChrome/lighthouse/issues/2274).
