### ISSUE TITLE
[SEO Audits] Content best practices group

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3117]
**Group name:** Content Best Practices

**Description:** Format your HTML in a way that enables crawlers to better understand your app’s content.

**Audits:**
- [x] Document has a `<title>`
  - reuse [document-title.js](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/accessibility/document-title.js)
- [x] [Document has a `<meta description>`](https://github.com/GoogleChrome/lighthouse/issues/3175)
- [x] [Document has a valid `hreflang` code](https://github.com/GoogleChrome/lighthouse/issues/3177)
- [x] [Document has a `rel=canonical`](https://github.com/GoogleChrome/lighthouse/issues/3178)
- [x] [Anchors have descriptive text](https://github.com/GoogleChrome/lighthouse/issues/3179)
- [x] Images have `alt` text
  - reuse [image-alt.js](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/accessibility/image-alt.js)
- [x] [Avoids plugins](https://github.com/GoogleChrome/lighthouse/issues/3180)

**Comment by kdzwinel** [comment]
@rviscomi done 🙌
