### ISSUE TITLE
[SEO Audits] Write documentation

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#4355]
Some SEO audits point to existing support documentation and other external sources. We want to have documentation of all of Lighthouse’s audits in one canonical place (d.g.co/tools/lighthouse or jsdoc). Additionally, we should use these LH-specific docs to describe the exact pass/fail conditions for each audit and guidance on how to fix common failure reasons.

@kaycebasques, feel free to work with @kdzwinel on any implementation details of the audits and reach out to Lizzi for peer reviews.

**Documentation checklist:**
- [x] Document has a `<title>`
- [x] Images have `alt` text
- [x] Has a `<meta viewport>`
- [x] Page has successful HTTP status code
- [x] Document has a `<meta description>`
- [x] Document has a valid `hreflang` code
- [x] Document has a `rel=canonical`
- [x] Anchors have descriptive text
- [x] Avoids plugins
- [x] Document uses legible font sizes
- [x] Page is not blocked from indexing
- [x] [robots.txt is valid](https://github.com/GoogleChrome/lighthouse/issues/4356)
- [x] [Tap targets are sized appropriately](https://github.com/GoogleChrome/lighthouse/issues/4358)
- [ ] [JSON-LD structured data is valid](https://github.com/GoogleChrome/lighthouse/issues/4359)

This list will be updated as we add more SEO audits.

**Comment by rviscomi** [comment]
@kaycebasques I see there were PRs to add docs for the [legible text](https://github.com/google/WebFundamentals/pull/5810) and [descriptive anchors](https://github.com/google/WebFundamentals/pull/5813) audits. Have these audits' descriptions also been updated to point to the new docs? Just trying to get a sense of progress on this issue.

**Comment by rviscomi** [comment]
@kaycebasques looking at the checklist in the first comment, there are two items unchecked:

The [robots.txt audit](https://github.com/GoogleChrome/lighthouse/issues/4356) is done and ready for docs. Are you able to work on this?

@kdzwinel is still working on the [tap targets audit](https://github.com/GoogleChrome/lighthouse/issues/4358) but we'll also need docs for that when ready.

**Comment by kaycebasques** [comment]
Yes, I can work on the robots.txt doc

**Comment by rviscomi** [comment]
Thanks! FYI I also added a checkbox for the [JSON-LD](https://github.com/GoogleChrome/lighthouse/issues/4359) audit which is also in progress. If you have time, we can start on these docs as well, but we'd need to delay publishing them until their respective audits are released.

**Comment by rviscomi** [comment]
FYI #4358 has been merged so we're ready for the docs

**Comment by exterkamp** [comment]
@mfriesenhahn should #9537 close this? Does web.dev have full coverage of all the bullet points above?

**Comment by mfriesenhahn** [comment]
> @mfriesenhahn should #9537 close this? Does web.dev have full coverage of all the bullet points above?

Yep, web.dev has a doc for each bullet. #9537 takes care of most of them, with the following exceptions:
- #9084 includes "Document has a `<title>`" and "Images have `alt` text."
- #9539 includes "Has a `<meta viewport>`."

I'm still tidying up the web.dev docs to address feedback from the Lighthouse team, but I expect to have the SEO ones done in the next day or two.

**Comment by Playback80** [comment]
https://github.com/GoogleChrome/lighthouse/issues/4355#issue-291698635

**Comment by Wmendes86** [comment]
preciso de ajuda
