### ISSUE TITLE
[meta] 2018 I/O Burndown

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#5008]
Channeling our ancestors, we introduce this year's abbreviated I/O burndown list. Also, heads up there are some duplicate checkboxes between here and #4333.

### LHR / Config / API [bckenny]
- [X] decide on groups/tags/scoredisplaymode
- [x] Submit lhr-lite CL to oneplatform #4867 
- [x] node module return is `{lhr, artifacts}` #4999
- [x] support 'html'/'csv' output from node module #4999
- [x] String/printf `displayValue` [@phulce] #5099 
- [ ] Introduce new `details`'s `type:'metric'` 
- [X] Introduce new `details`'s `type:'opportunity'` #5296
- [x] Update scoreDisplayMode, remove booleans, support null scores #5105 
- [x] rename perf-hint => `opportunities`, perf-info => `diagnostics`, perf-metric => `metrics` #5102 
- [x] Introduce `manualDescription` #5100 
- [x] update metrics.js output to be consumable from HTTPArchive. #5101 
- [ ] LHR extends LHR-lite
- [x] Remove `extendedInfo` #4614
   - [x] Initial: exclude it from LHR via `createAuditResult` but audits still report (so our audit tests don't need massive updates
   - [ ] Take inventory of extendedInfo data that's currently not in the associated `details` block, but should be.  (here's [what HA uses](https://github.com/HTTPArchive/beta.httparchive.org/search?utf8=%E2%9C%93&q=audits&type=), what [brendan uses](https://github.com/brendankenny/bq-har/search?utf8=%E2%9C%93&q=extendedInfo&type=))
   - [ ] Update all those tests
- [ ] Apply necessary LHR-lite naming changes #4983:
  * [x] `initialUrl` -> `requestedUrl`, `url` -> `finalUrl` #5127
  * [x] `fetchedAt` -> `fetchTime`, remove `generatedTime` #5112
  * [x] `reportCategories` -> `categories`, `categories` from arrays to keyed objects #5155 
  * [x] `reportGroups` -> `categoryGroups` #5155 
  * [x] `runtimeConfig` -> simplified settings in LHR and create runtimeConfig in report renderer #5122
  * [ ] remove `Category.id` (maybe don't need)
  * [x] `category`: `name` -> `title`, `audits` -> `auditRefs` #5157
  * [x] `audit`: `name` => `id`, `description` -> `title`, `helpText` -> `description`
  * [x] `debugString` -> `explanation` #5132 
  * [x] `debugString` sometimes `errorMessage` instead #5132
 - [ ] make score required part of `Audit.product` instead of `rawValue`. Get rid of `rawValue` (if we can agree on place (details?) to put metric raw values)

### Breaking core changes/Lanternification [phulce]
- [x] Switch to lantern-run by default #5041 
- [x] make TTI adjustments (FCP-based, network quiet fixes, etc) #5021 
- [x] Lantern-based EIL #5024 
- [x] All opportunities work with Lantern
    - [x] render blocking #4995 
    - [x] redirects #5081
    - [x] rel preload #5062 
    - [x] preconnect #5070 
    - [x] use max(TTI, end of load) for savings #5084 
    - [x] offscreen images #5084 
- [x] Score: apply new scoring #4629 #5083 

### Report redesign [paulirish]

_see [Lantern UX - Google Slides](https://docs.google.com/presentation/d/1wc6PwZoCawptqoFWiApXQhoFslvVesAi2oQvUVuEeKQ/edit) 🔐  and [Lighthouse Report - Gallery](https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZaIO075l8EaD/files/MCFlTfxxBeOyReF7XLtPQTiw) 🔐_

- [x] Revised Score gauges. Category score legend
- [x] Rich tooltips for scores and metrics
- [x] Use rich tooltip for audit errors #5077 
- [x] Metric display. 
    - [x] new table layout. icons. 
    - [x] Heading and disclaimer text
- [x] Diagnostics display #5109
   - [ ] audit list indexes should be cumulative within categorySections (pass/fail/notApplicable even when there are groups within those)
- [x] Opportunity display #5115
- [x] new details table display (toggle arrow and column headers)
- [x] Fix focus outline oddness (toggle-arrow and tooltip interaction)
- [x] Filmstrip?
- [x] Adopt tooltip for learnMore text. Improve the usability of that text.
- [x] Change to branded header
- [ ] write renderer tests for all audit/error/displayMode/debugString/warning/explanation combinations.
- [x] warnings/displayValue rendering: #5153

### Roll out 3.0 [paulirish@, phulce@]
- [x] ~~Release alpha version of 3.0 prior to I/O for internal testing (sometime during week of 5/2).~~
- [x] Roll out 3.0 to CLI as a release candidate 
- [x] Roll out 3.0 to Chrome Extension as default 
- [x] Add Lantern opt-put to Chrome Extension under 'Options' (Hwi to create mock). 
- [x] ship 3.0 final to CLI

### Core
- [ ] Move computed artifacts off `artifacts.*`. Require them explicitly instead of `fs.readdir` bizness
- [ ] Use LHError for all thrown errors when possible (connections/cri.js for example)
- [x] replace --perf with a real mechanism for using full/perf/mixed-content configs #5041 
- [x] Generate closure externs for reportrenderer for DevTools. Update its JSDoc for TS. Thus, enabling compilation with both TS & CC
- [x] Smoketests work with lantern

### LHR  
- [x] Fix allowed config representations (config v2 😃 , i.e. no more `audits: ['path/my-audit']` -> `audits: { 'my-audit': {path: 'path/to/audit'}}`)
- [x] Use `fallbackKey`/`fallbackValueType` for multi-typed columns (code snippets sometimes instead of URLs)?

### Report
- [ ] Split opportunities by First Paint improvements and "Load Improvements"

## 🏈 🏖 Punt till after I/O

- [ ] Update default device settings
   - [ ] Throttling: change the preset #4594 
   - [ ] Change device from Nexus 5X to Pixel?
- [x] Roll out 3.0 to Lighthouse on DT

## 🐞from I/O
- [x] freezes on https://emojityper.com/
- [ ] font display audit shows non-lantern download time
- [x] Unused CSS Rules/Minify Css audit name inconsistent
- [ ] tons of warnings on www.ctvnews.ca
- [x] minimum timeline scale should be ~3-10s
- [x] minimum opportunity scale should be ~2s
- [x] first audit is misaligned
- [ ] "is on https" audit shouldn't fail if it redirects
- [ ] Third party filter in the report
- [ ] Third party blame report (to the LH user, or better, at a web-wide level)

**Comment by vinamratasingal** [comment]
I added stuff for tracking the release process @paulirish @patrickhulce @brendankenny FYI. 

Let me know who to assign as the owner.
