### ISSUE TITLE
Internationalization of Lighthouse (Phase 1)

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#5719]
Through a series of PRs and CLs we're much closer to having Lighthouse i18n-ready than before. Some relevant PRs: #5644, #5655, #5713, #5716, #5718 

### Known remaining work:

- [x] Dump workflow established. xtb dump -> json -> LH core locale files @paulirish 
- [x] Add `[ICU Syntax]` to all descriptions of fields that use icu message syntax. it can start or end with this label string @paulirish #5736
- [x] Pass locale to toLocaleString calls in renderer @patrickhulce @brendankenny #5734 
- [x] Figure out locale fallback. (PSI user with locale pt-PT should get pt, not en-US). Where does this happen? @brendankenny  #5746
- [x] Add descriptions to ALL strings (enabled by #5718) @patrickhulce @brendankenny @paulirish
- [x] Refactor renderer use of Util.UIStrings in reportRenderer. Instead of setup/breakdown, use a str() method which chooses between provided renderer strings and fallbacks defined in Util.UIStrings.
- [x] (psi) Expose a Util.prepareLHR() method
- [x] fix icumessageinstanceid string in extension category setup
- [x] Roll TC locales back into gh repo #5780
- [x] Address remaining english strings in report:
   - [x] CRC template @patrickhulce @paulirish #5730
   - [x] UserTiming has 4 strings #5806
   - [x] ~runtime settings~ PUNTED
   - [x] ~export dropdown (low pri)~ PUNTED
- [x] Text-expansion (`de`) UI review
- [x] Use placeholders for our use of `origin`? See https://goto.google.com/gnjrf
  - [x] Confirm non-translated strings (eg. "origin", product names) are as expected. URL can be translated.
- [x] address TC locale fallback story 
- [ ] figure out Node's ICU support on Travis/Appveyor (`Number.toLocaleString` appears to always use `'en-US'` - [Travis failure](https://travis-ci.org/GoogleChrome/lighthouse/builds/410104347#L933-L986)) 
   - presumably the node install is [system-icu or small-icu](https://nodejs.org/api/intl.html#intl_options_for_building_node_js)
   - can we resolve with an NVM flag or travis config? 
- [x] temporarily exclude locale json files from ext build

### ship l10n'd lighthouse to extension/devtools
- [ ] localize error messages. #6441
- [ ] RTL layout @paulirish
- [ ] `lang` attribute #5805
- [ ] include locale json files in build

Plz add anything else here

**Comment by brendankenny** [comment]
>> figure out Node's ICU support on Travis/Appveyor (`Number.toLocaleString` appears to always use `'en-US'`)

> can we resolve with an NVM flag or travis config?

looks like yes we can, but have to pass `--with-intl=full-icu` to `nvm` manually instead of relying on travis's built-in version selection.

See https://github.com/travis-ci/travis-ci/issues/9422#issuecomment-377953406 and https://github.com/creationix/nvm/issues/1719.

I haven't looked into appveyor yet.

**Comment by oncletom** [comment]
Newest release of nvm should address https://github.com/GoogleChrome/lighthouse/issues/5719#issuecomment-418467626

**Comment by paulirish** [comment]
We call this one done, folks. 👍 👍 👍 👍 👍 

#7238 "Internationalization of Lighthouse (Phase 2)" paints the road ahead.
