### ISSUE TITLE
tsc: don't rely on implicit index signature for objects

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#5873]
tracking issue for updates needed for the upcoming TypeScript 3.1, [which will no longer](https://github.com/Microsoft/TypeScript/pull/25996#issuecomment-408284828) automatically add `[x: string]: any;` to any type inferred from an object declaration. This is only a change for js; this was never done in ts.

It was helpful in cases where we were mapping specific small objects to a general grab-bag type (e.g. `{type: 'code', snippet: str}` and then saying it was of a more general details item type), and we'll have to explicitly declare a few more types to fix those places.

But it means certain errors will now be caught. e.g. in TS≤3.0 in `lighthouse-ext-background.js`, if you refer to `background.getDefaultCategories()` the return value will be type checked, but if you do `background.getCategoriez()` the compiler will think the call is valid and returns an `any`, because the compiler was automatically adding a `[x: string]: any;` to the [`lighthouse-background.js` export](https://github.com/GoogleChrome/lighthouse/blob/020333031f66684c4c153d080fc42b29c384f732/lighthouse-extension/app/src/lighthouse-background.js#L65-L70).

Before I started we had almost 100 errors from this, and fixing them only makes things more correct (even in 3.0), so I thought I'd start early. In many places a single line fix and multiple errors are resolved, so it shouldn't be too bad.

- [x] config files ~#5858~
- [x] mainthread-work-breakdown/task-groups ~#5859~
- [x] many places ~#5874~
- [x] traceOfTab (and fix optional properties) ~#5887~
- [x] LHError ~#5896~
- [x] `load-simulator`/`simulator.js` ~#5897~
- [x] Viewer ~#5942~
- [x]  `DetailsItem`

**Comment by brendankenny** [comment]
This is complete with #5942 (though detailsItem still needs work independent of this)
