### ISSUE TITLE
☂️ 👣 Breaking changes for next major

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6202]
A la #4333, the items we are thinking of changing in the next major rls

 - [x] PWA audit reorg #6395
 - [x] displayValue should always be string #6200 
 - [x] proto changes `not_applicable` #6201
 - [ ] benchmarkIndex => CPU throttling #6162
 - [x] Lr_desktop is too generous #6836
 - [x] Nexus5x viewport is slightly different #6615
 - [x] remove children from crc #6211 
 - [x] Rename `typings/` to `types/` #6617
 - [x] Rename `core/gather/computed/` to `core/computed/` #6618

Punt?
 - [x] remove `rawValue` #6199

**Comment by brendankenny** [comment]
this is old now. See #7752 :)
