### ISSUE TITLE
PWA category refactor tracking issue

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#6395]
#### Fast and Reliable
- [x] Page load is fast enough on mobile networks (TTI < 10s)
- [x] Current URL responds with a 200 when offline
  - [x] rename: "Current page responds with a 200 when offline" #6494
- [x] start_url responds with 200 when offline - #6397

#### Installable
- [x] Uses HTTPS (either localhost or has valid certificate)
- [x] Registers a service worker
  - [x] check that test page URL is in SW scope #6609
  - [x] check that `start_url` is in SW scope #6678
- [x] Manifest requirements (starturl, name, display, icons) #6630

#### PWA Optimized
- [x] rename group #6494
- [x] Redirects HTTP traffic to HTTPS
  - [x] ~should be in a different group?~ (deferring question for now)
- [x] Is not configured for a custom splash screen
- [x] Address bar does not match brand colors
  - [x] needs a rename #6494
- [x] Has a <meta name="viewport"> tag with width or initial-scale
- [x] Content is sized correctly for the viewport
- [x] Contains some content when JavaScript is not available

#### Manual
- [x] Page transitions don't feel like they block on the network
- [x] Site works cross-browser
- [x] Each page has a URL

### Next:
- [x] add groups to default-config - #6396
- [x] Badging!
  - [x] Add grayscale group badges #6486, #6686
  - [x] Change to filled-in badges when group is passing - #6504, 
  - [x] Replace score gauge with badged gauge - #6526, #6670
- [x] Add adequate vertical spacing between audit groups (see [comment](https://github.com/GoogleChrome/lighthouse/issues/6395#issuecomment-439259634)) - #6688
- [x] Score gauge tooltip (see [comment](https://github.com/GoogleChrome/lighthouse/issues/6395#issuecomment-439562286)) - #6689
- [x] No more passed audit hiding 
  - [x] Refactor of current category-renderer to support new use cases #6460, #6482, #6594 
  - [x] Add pwa-category-renderer, don't hide passed audits #6486 

### Lighthouse v5
- ⁅ ⁆ Figure out LHR/scoring story

**Comment by hwikyounglee** [comment]
And we landed on "PWA Optimized" 
cc: @kusler @paulirish  💅

**Comment by kusler** [comment]
What about 'Enhancements'?

**Comment by kusler** [comment]
Refinements
Further Improvements
?

**Comment by hwikyounglee** [comment]
I'm hoping the word is useful when we say something like, "Making it Reliable and Fast, Installable, and PWA Optimized can help your app provide a great app experience."

**Comment by kusler** [comment]
Hmm... But isn't it a little redundant because it's already in the PWA section?

**Comment by patrickhulce** [comment]
FWIW, here are some of my thoughts. That section is a grab-bag of things that make the app feel not terrible. They're baseline things that make it more like how a professional, well-put-together, native-like app would feel. These are the words that come to my mind when I think about the audits in there

Usable
Presentable
Cohesive
Snazzy

**Comment by hwikyounglee** [comment]
Hoping it to feel more action-oriented i.e. [the word] is done to the app by the developer.
Something about 'Polished' didn't sound right to me, it's probably because it describes both action and perception by others. I still feel 'Optimized' is a nice balance. If it causes a confusion, we can continue to iterate on it. 

Would 'Refined' work?

**Comment by brendankenny** [comment]
I went with "PWA Optimized" for now as a compromise, but I'll throw my vote in for "Polished" as well :)

> If it causes a confusion, we can continue to iterate on it.

We'll need to do this fairly quickly, since we'll want to have it locked down by 4.0 (so, this week :).

We *can* have a different group name from group id and so be able to change what's displayed in the future, but it would be nice to have them not *too* far apart.

**Comment by exterkamp** [comment]
From CR in #6486:

I feel like a fill of `#ffffff` is too low contrast/I don't like the color combo, and `#5e6268` is too dark with these very filled in icons.  I prefer a lighter grey like `#a3a7ae` or something like that.  This is all semantics tho.

Top is current, middle matches all other icon fill colors, bottom is a softer grey.
![image](https://user-images.githubusercontent.com/6392995/48097155-e7e6ad80-e1cd-11e8-89e2-b5d9fdebf086.png)

**Comment by hwikyounglee** [comment]
- Category name:  "PWA Optimized" SGTM
- Icon color:  we can try `#cfd8dc` for the BG color. I would keep the icon shape in white. If it's filled with a color, it looks like it's already fulfilled.

**Comment by patrickhulce** [comment]
Ooooooo "Polished" is exactly what I was searching for :)

**Comment by hwikyounglee** [comment]
"Polished" seems to have a notion of perception by others (i.e. feels judged a bit).

**Comment by brendankenny** [comment]
@paulirish [commented](https://github.com/GoogleChrome/lighthouse/pull/6526#discussion_r234378230)

> I'm wondering if we should also clarify the state in a tooltip.
> 
> We could do with a full lh-tooltip and bulleted list, but here's a minimal `[title]` example: 
![image](https://user-images.githubusercontent.com/39191/48652605-39a0ec00-e9b5-11e8-8931-04f32eec814a.png)

**Comment by hwikyounglee** [comment]
Alternative idea:
Fast and reliable: 3/3, Installable: 3/3, PWA Optimized: 4/6

**Comment by hwikyounglee** [comment]
re: vertical spacing 

+1 to using the same spacing for other categories. Vertical spacing could help with seeing a long list with visual grouping.

**Comment by brendankenny** [comment]
> re: vertical spacing

ok, great. I'll add it to the list 👍

**Comment by brendankenny** [comment]
💥 💥 💥 💥
