### ISSUE TITLE
Gatherer/artifact cleanup

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6747]
In a plugin world, the gatherers become part of our public API. We know about a few things we're interested in changing. Let's capture them here.

* [x] add a new `MetaElements` gatherer which gets name/content of all of them. This would nullify the following: `ThemeColor`, `Viewport`, `MetaRobots`, `MetaDescription`, (#7025)
* [x] add a new `LinkElements` gatherer (..actually introduced in #6694 as `ExternalResourceLinks`). This could nullify `Canonical` and `Hreflang` (#7080)
* [x] add a new `AnchorElements` gatherer which gets rel/href/target/text of all `a` elements, nullifies `AnchorsWithNoRelNoopener` and `CrawlableLinks` (#7101)
* [x] convert `ImageUsage` into `ImageElements` gatherer (#7030)
* [x] convert `Scripts` into `ScriptElements` gatherer (#7920)
* [ ] ...

~~@patrickhulce you had a few in mind, too, right?~~

**Comment by patrickhulce** [comment]
`meta` and `links` were the two big ones 👍 I also wanted to cleanup

- `Images` into `ImageElements`
- `AnchorElements`

**Comment by patrickhulce** [comment]
I like the standardization on `*Elements` I'll update #6694, my only concern with `LinkElements` was that it would be easily confused with `a` elements :) I think it makes sense though when they'll be side-by-side

**Comment by kusler** [comment]
Is this issue comprehensive with what we're wanting to accomplish with artifact cleanup, or are there more that need to be tended to? 

If it's not the full list, then can Connor take on fleshing it out?

**Comment by patrickhulce** [comment]
I think the primary goal is getting our artifacts in a state ready and useful for plugins. If someone wants to do some brainstorming what audits might need to know about a page and how we should standardize it, that'd be super useful :)

**Comment by patrickhulce** [comment]
OK decision time and input needed! Over in https://github.com/GoogleChrome/lighthouse/pull/8133#discussion_r274014854 we were discussing exposing the DevTools-style child-index path on the `ScriptElements` artifact. This brings up a host of discussions about our public API for artifacts in v5.


My proposal is **we only expose `*Elements` artifacts and the base artifacts to plugins by default**. This will give plugins access to network records and the primary elements on the page which should take you pretty far. Everything else we make opt-in via `dangerouslyUseExperimentalArtifacts` or an `Experimental` prefix in the artifact name or something.

Most of the artifacts were written for specific audits in mind and by exposing them to arbitrary usage I think we run the risk of folks accidentally using the wrong thing or in a way we didn't intend and coming up with wrong results and/or stuck supporting a use case we never wanted to support. This is somewhat similar policy to the devtools protocol methods, making our BaseArtifacts + Element artifacts our "v1 stable" protocol.

In addition, I think certain properties on our elements should become "private". For example, the only purpose of the devtools-specific child-index node path is for node revealing, so until we support plugins in Devtools (feels a ways off), there is no need to expose that under a generic property name of `path` and have folks start relying on it for some other purpose.


Thoughts on this proposal? Any objections?

https://github.com/GoogleChrome/lighthouse/blob/b374ea409fc56fa1af7af8e9f3a5c6c1f96ee30d/types/artifacts.d.ts#L21-L48

**Comment by brendankenny** [comment]
This is more or less done for 5.0 in `PublicGathererArtifacts` (and `BaseArtifacts`). Growing the public artifacts will be an ongoing project.

See the number of links above for PRs where this was done and [plugins.md#available-artifacts](https://github.com/GoogleChrome/lighthouse/blob/master/docs/plugins.md#available-artifacts) for developer information on using the artifacts.
