### ISSUE TITLE
☂️ Proto Convergence Tracking

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#6801]
Making a tracking bug for proto -> LHR convergence.  Some issues already covered by #6202 but there are more long pulls.

- [x] displayValue should always be string #6200
- [x] proto changes not_applicable #6201 
- [x] deprecate not_applicable from proto (Cannot do, it is enum)
- [x] convert not_applicable field number (4) to reserved field number (Cannot do, it is enum, but made the alias for it)

**Comment by exterkamp** [comment]
For 4.0 and 4.1 this is done.  We can make a new tracking issue if major branches happen in format.
