### ISSUE TITLE
Internationalization of Lighthouse (Phase 2)

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#7238]
Picking up after #5719 

### Known work
- [x] bring back https://github.com/GoogleChrome/lighthouse/pull/5726/files#diff-4bcfedf0736e1cd08b26fe659537ad90 to avoid #7010. #9192 
- [x] figure out Node's ICU support on Travis/Appveyor (`Number.toLocaleString` appears to always use `'en-US'` - [Travis failure](https://travis-ci.org/GoogleChrome/lighthouse/builds/410104347#L933-L986)) 
   - presumably the node install is [system-icu or small-icu](https://nodejs.org/api/intl.html#intl_options_for_building_node_js)
   - can we resolve with an NVM flag or travis config? 
   - or better polyfilling. Fix in #9584
- [ ] revamp i18n.lookupLocale and locale list to better canonical lookups
  - [ ] `Intl.NumberFormat.supportedLocalesOf(['no', 'tl']) === []`, so even though we support those locales in translations they get the wrong (?) number formatting, plurals, etc by falling back to a default locale (`en`, probably). Why do these in particular fail but all the others work?
- [ ] text baked into the report HTML
  - [ ] export dropdown #9166 
  - [x] ~~header metadata~~
  - [ ] footer runtime settings #9166 
  - [ ] `Number.toLocaleString` _all_ numbers in report
    - [ ] scorescale!
  - [ ] aria labels
- [ ] a11y manual audits
- [ ] Translating strings from gatherers (error messages, etc)

### finish complete l10n of lighthouse
- [x] localize error messages. #6441
- [x] localize remaining categories
  - [x] seo
  - [x] best-practices #9092 
  - [x] pwa #9105 
- [x] localize stack packs?
- [ ] move pwa audits to `audits/pwa` folder
- [ ] move best-practices audits to `audits/best-practices`
- [ ] RTL layout @paulirish
- [ ] `lang` attribute #5805
- [ ] include locale json files in build
- [ ] warnings
- [x] Date/Time Locales #1703
- [ ] PSI swap langs? :open_mouth:  [this guy wants it](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/yKPCNPrpK2E)
- [ ] `proto` refactor i18n section.  @past-shane you really messed this one up.
- [x] Placeholder syntax #9114 to prevent #9000
  - [x] fix i18n guffaws #9197 
- [x] es-419
- [ ] viewer locale swap?
- [ ] read locale info from system? e.g. #1703
- [ ] i18n concat'd lists, like [this](https://github.com/GoogleChrome/lighthouse/pull/9105/files#diff-fe74cb7bc5d0a64791a6225d735d9503R56)

### ship it
- ~~[ ] ship l10n'd lighthouse to extension~~
- [ ] ship l10n'd lighthouse in devtools audits panel
- [ ] enable web.dev to use full l10n'd lhrs if they want

Plz add anything else here

**Comment by exterkamp** [comment]
Added some things that are todo

**Comment by brendankenny** [comment]
> Number.toLocaleString all numbers in report

Answer to this is
https://v8.dev/features/intl-numberformat#units

```js
const formatter = new Intl.NumberFormat('en', {
  style: 'unit',
  unit: 'kilobyte',
});

formatter.format(1.234);
// → '1.234 kB'
```

Conveniently it's in V8 7.7, which is the version shipping with the new Node 12.13, which became the LTS release in October. When we switch to node 12 as the new minimum in the spring or whenever, we can start using that.

**Comment by brendankenny** [comment]
We should also investigate what of our ICU polyfills can be dropped now that https://github.com/nodejs/node/pull/29522 has landed.

**Comment by connorjclark** [comment]
@exterkamp and I discussed a desire to move the localization into the report renderer. Involves the LHR strings always being english, bundling all the locales in the report renderer (we could look into code splitting too), and doing the `swap locales` logic in the report (done based on user locale initally, but also exposed via a setting within the report).

wins:

* allows for the same report to be shared in multiple languages
* allows for the user to easily override what the channel thought their preferred language was
* would allow us to drop the `RendererFormattedStrings` in the proto
