### ISSUE TITLE
☂️ 👣 Breaking changes for v5

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#7752]
A la #6202 and #4333, the items we are thinking of changing in the next major rls

 - [x] Kill `rawValue` #6199 (PRs #8343, #8385, #????)
 - [x] Remove `disableDeviceEmulation` flag before v5 #7044 (PR #8289)
 - [x] (minor) Inconsistent format of screenshot-thumbnails and final-screenshot #7092 (PR #8299)
 - [x] Switch to a different name for [`LH.Audit.Details.Diagnostic`](https://github.com/GoogleChrome/lighthouse/blob/7a431253ff19397d4b8db9ccdf599e93f7fe40c6/types/audit-details.d.ts#L78). "Diagnostic" is too [overloaded](https://github.com/GoogleChrome/lighthouse/blob/7a431253ff19397d4b8db9ccdf599e93f7fe40c6/lighthouse-core/config/default-config.js#L31) in LH. (PR #8298)
 - [x] Move to minimum Node 10 #7215 (PR #8117)
 - [x] Turn on advanced LR network timings (PR #8109)
 - [x] Lantern FCP improvements (PR #7513)
 - [x] Collect only elements in body for `dom-size` (PR #7241)

**Maybe:**

**Punted: 🏈**
 - benchmarkIndex => CPU throttling #6162
 - Consider always filtering configs #7787

**No:**
 - ~Expose page functions to custom gatherers #7317~
 - ~drop null from `SharedFlagsSettings` properties #7788~

Please add any additional above.

**Comment by brendankenny** [comment]
one bullet point might be to decide on our v5 public interface, at least the start of one. This could also involve finally publishing the our public types :)

I bring this up because

> Expose page functions to custom gatherers #7317

Right now we're reluctant to call even artifacts a public interface since it will make some (even minor) changes a lot harder. We should be judicious in what we expose because we can't tweak or take them back later.

Page functions are short enough (and usually self contained enough) that they could be a good candidate for a list of "useful functions you might want to copy/paste" if we didn't want to commit to their current form, for instance.

**Comment by benschwarz** [comment]
Thanks for posting. We'll be tracking against this.

**Comment by exterkamp** [comment]
Are we going to touch rawValues at all for v5?

**Comment by patrickhulce** [comment]
oh yeah let's make the `.details.timeInMs` or whatever a thing :)

**Comment by exterkamp** [comment]
> benchmarkIndex => CPU throttling #6162

This is out, right?

**Comment by patrickhulce** [comment]
@exterkamp ya, I'll go ahead and close the PR actually.

**Comment by brendankenny** [comment]
These are complete! Any further breaking changes we come across we should add to #8331.

If you retroactively realize we already added a breaking change, please also add those #8331 so they will be easier to document in the 5.0 changelog.
