### ISSUE TITLE
[meta] 2019 I/O Burndown

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#8331]
Channeling our [ancestors](https://github.com/GoogleChrome/lighthouse/issues/5008), we introduce this year's abbreviated I/O burndown list.

## Report
- [ ] Redesign #8185
- [x] Improved report handling in g3 #8197  [@exterkamp]
- [x] ensure 4.x LHR and 5.0 report renderer compatibility #8598
- [x] third-party table filtering #6351

## Core
- [x] Ship LightWallet / Perf Budgeting [@khempenius]
   - [x] [Learn more] link for lightwallet audits https://github.com/GoogleChrome/lighthouse/pull/8522#discussion_r279479493 (PR #8871)
   - [x] smoke test(s) (PR #8853)
- [x] Ship 4.3.0 [@hoten]
- [x] Ship 4.3.1 [@hoten]
   - [x] merge 4.3.1 in devtools to beta (https://crbug.com/958952)
- [x] Ship 5.0
   - [x] PSI rls notes and announcement [@exterkamp]
   - [x] Changelog highlighting major (interesting) and breaking changes, screenshots, etc
   - [x] update Chrome Webstore extension screenshots #6112
   - [x] ship 5.0 to devtools
- [x] Lighthouse v5 Breaking Changes #7752 [@brendankenny]
   - [x] Kill `rawValue` #6199 (PRs #8343, #8385, #8421)
   - [x] Remove `disableDeviceEmulation` flag before v5 #7044 (PR #8289)
   - [x] (minor) Inconsistent format of screenshot-thumbnails and final-screenshot #7092 (PR #8299)
   - [x] Switch to a different name for [`LH.Audit.Details.Diagnostic`](https://github.com/GoogleChrome/lighthouse/blob/7a431253ff19397d4b8db9ccdf599e93f7fe40c6/types/audit-details.d.ts#L78). "Diagnostic" is too [overloaded](https://github.com/GoogleChrome/lighthouse/blob/7a431253ff19397d4b8db9ccdf599e93f7fe40c6/lighthouse-core/config/default-config.js#L31) in LH. (PR #8298)
   - [x] Move to minimum Node 10 #7215 (PR #8117)
   - [x] Lantern FCP improvements (PR #7513)
   - [x] Collect only elements in body for `dom-size` (PR #7241)
   - [x] New a11y audit weights (PR #8823)
   - [x] `apple-touch-icon` audit increases PWA "optimized" requirements #7890 (PR #8857)
- [x] New audits
   - [x] replace EIL with MP-FID (PR #8729)
   - [x] PWA: `apple-touch-icon` audit #7890 (PR #8857)
   - ~others?~
- [x] Stack Packs [@exterkamp]
   - [x] i18n #8154 [@exterkamp]
   - [x] Reimport translations [@exterkamp]  
   - [x] lhr.stackPacks proto compatibility #8245
- [x] Strings @exterkamp
  - [x] seo groups #8378 
  - there are strings not getting translated, but all minor.
- [x] Plugins [@brendankenny]
   - [x] artifact cleanup [@patrickhulce] #6747 
   - [x] only allow audits to use what they declare as requiredArtifacts (PR #8760)
   - [x] Publish plugin guide (PR #8728)
- [x] Ship a new chrome-launcher
   - [x] https://github.com/GoogleChrome/chrome-launcher/pull/142
   - [x] https://github.com/GoogleChrome/chrome-launcher/pull/138 ?
   - ~others?~

## Lightrider
- [x] PWA in LR & web.dev [@hoten]
  - [x] service workers functional in WRS
  - [x] resolve offline-ready bug (#8350) (b/128446845#comment2)
- [ ] LR Smoke Inconsistencies [@hoten]
- [x] Enable Config in LR for Smokerider [@hoten]
- [ ] Define Deprecation Plan PSI for v1-4 (and begin) [@exterkamp]
- [x] LR APAC Deployment [@exterkamp]
- [ ] Adjust 100s PSI Quota [@paulirish]
- [x] Add stack packs to Apiary and PSI [@exterkamp]
- ~Turn on advanced LR network timings (PR #8109)~
  - [x] Reverted in PR #8752

## General
- [ ] FCP p90 Thresholds [@paulirish]
- [ ] Publish and link Variance documentation #8594  [@paulirish]
- [ ] Investigate and fix bugs [TEAM EFFORT]
- [x] Extension Remove bug reporting flow (#8294) [@wardpeet]
- [x] Plugin documentation - getting started #8728  [@patrickhulce]

## Punting till after I/O
- [ ] Report diff [@hoten]
- [ ] CI [@patrickhulce]
- [ ] BenchmarkIndex => throttling calibration [@exterkamp]
- [ ] LR Variance Effort  [@exterkamp]
- [ ] "Task Queue is Full" / raise practical headroom  [@paulirish]
- [ ] setting for category order in report
- [ ] Screenshot.sampling trace category [@hoten]
- [ ] Plugins
   - [ ] load plugins to validate artifacts #8381 
   - [ ] config: filter out unused gatherers (likely just turn off the onlyAudits/onlyCats check) #7787
 - [ ] Maybe commit to an initial public interface and publish types? #1773
 - ~Maybe drop null from `SharedFlagsSettings` properties #7788~

**Comment by brendankenny** [comment]
Closing. Remaining issues:
a) missed the deadline
b) are tracked elsewhere :)
