### ISSUE TITLE
Audits Meta: Feature parity with PSI, MFT, DevTools

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#909]
_updated by @paulirish jan 2018_ 

### For parity with [Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights/)

- [x] Eliminate render-blocking JavaScript and CSS in above-the-fold content ([docs](aaaaaaaa))
- ~Prioritize visible content~ ([docs](https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent))
  - not pursuing the exact definition of the original audit
  - [ ] reduce size of above-the-fold content
  - [x] large off-screen images #1807
- [x] Leverage browser caching #3460 ([docs](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching))
- [X] Enable compression ([docs](https://developers.google.com/speed/docs/insights/EnableCompression))  #1513
- [x] Minify CSS, Minify JavaScript #3459 ([docs](https://developers.google.com/speed/docs/insights/MinifyResources))
- ~Minify HTML~
    - concluded the value is too low to pursue
- [x] Reduce server response time ([docs](https://developers.google.com/speed/docs/insights/Server))
- [x] Avoid landing page redirects ([docs](https://developers.google.com/speed/docs/insights/AvoidRedirects))
- [ ] Content is sized correctly for viewport ([docs](https://developers.google.com/speed/docs/insights/SizeContentToViewport)) (#1836)

### For parity with [Mobile-Friendly Test](https://search.google.com/search-console/mobile-friendly):

- [ ] Tap targets ([docs](https://developers.google.com/speed/docs/insights/SizeTapTargetsAppropriately)) (#4358)
   - basic tap target size detection that PSI does
- [x] Legible font sizes ([docs](https://developers.google.com/speed/docs/insights/UseLegibleFontSizes))
   - [docs](https://developers.google.com/speed/docs/insights/UseLegibleFontSizes)
- [x] Optimize Images ([docs](https://developers.google.com/speed/docs/insights/OptimizeImages))
   - we want to calculate the latency caused by unoptimized images.
- [x] Avoid plugins ([docs](https://developers.google.com/speed/docs/insights/AvoidPlugins)))
  - issue: #101 
- [ ] avoid interstitials ([docs](https://developers.google.com/webmasters/mobile-sites/mobile-seo/common-mistakes#avoid-interstitials))
   - cleanroom implementation needed 

### For parity with legacy DevTools Audit panel:

- [x] Unused CSS rules
  - dependent on the new css coverage backend that landed in early nov.
- [x] Styles & script order
   - see [auditrules.js](https://github.com/ChromeDevTools/devtools-frontend/blob/9a63b4b99287b3dcc11b485c532b780b43909fca/front_end/audits/AuditRules.js#L1055)

**Comment by paulirish** [comment]
some basic info added, more to come.

**Comment by patrickhulce** [comment]
after talking with paul, the styles & script order don't seem to really apply anymore. we came up with #943 instead. any thoughts or arguments for keeping those particular audit rules around @ebidel?

**Comment by ebidel** [comment]
Not from I. This seems like a good time to modernize them :)

**Comment by ebidel** [comment]
Updated the list with the css usage tracking. That's imminent.

**Comment by igrigorik** [comment]
Re, parity.. Looking at the list, I think there are two audits missing:
- https://developers.google.com/speed/docs/insights/AvoidPlugins - see https://github.com/GoogleChrome/lighthouse/issues/101.
- https://developers.google.com/speed/docs/insights/UseLegibleFontSizes

**Comment by ebidel** [comment]
Thanks @igrigorik. Added those to the top.

**Comment by brendankenny** [comment]
#1452 addresses unoptimized images, though it would be nice to have a place to track building on that to try to quantify the load time added by not using better compression.

**Comment by paulirish** [comment]
As of 2.8.0 nearly all the parity audits are complete! Boom.

**Comment by paulirish** [comment]
We good here. Follow the linked issues above for individual audits.
