### ISSUE TITLE
☔️  DevTools health check

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9199]
I've gotten many regression reports for stuff related to LH in DevTools. Many quirks of varying seriousness. Collecting them all here for visibility. Not all are restricted to just DevTools.

# DevTools only

## Critical
- [x] [Issue 968425: Regression:Unable to perform Audit on any website.](https://bugs.chromium.org/p/chromium/issues/detail?id=968425)
- [x] [Issue 981495: Regression: DevTools window becomes unresponsive after selecting 'Print Summary' option from 'Export report' overlay](https://bugs.chromium.org/p/chromium/issues/detail?id=981495)
- [x] [Issue 979126: Regression: Dev-Tools window is not seen when navigating to other website.](https://bugs.chromium.org/p/chromium/issues/detail?id=979126)
- [x] [dark mode seen in print preview](https://bugs.chromium.org/p/chromium/issues/detail?id=983425)

## Moderate

- [x] [Issue 981454: Regression: [DevTools] Web-page doesn't render properly on maximizing the Chrome window.](https://bugs.chromium.org/p/chromium/issues/detail?id=981454)
- [ ] [right click -> print on report does not print report](https://bugs.chromium.org/p/chromium/issues/detail?id=979139)

## meh

- [ ] [Issue 969631: Regression:[Devtools]Shadow of 'reload' icon is seen while recording activities in performance tab.](https://bugs.chromium.org/p/chromium/issues/detail?id=969631)
- [ ] [Issue 971586: Regression:Scrollbar is not visible on dev tools window after performing Audit.](https://bugs.chromium.org/p/chromium/issues/detail?id=971586)
- [ ] [Issue 972934: Regression : 'Audits' dialog box is seen chopped while resizing browser window towards LHS.](https://bugs.chromium.org/p/chromium/issues/detail?id=972934)
- [ ] [Issue 978801: Regression:Unnecessary extra white space is seen at the bottom of devtools window after performing audit.](https://bugs.chromium.org/p/chromium/issues/detail?id=978801)
- [x] [can't save as html](https://bugs.chromium.org/p/chromium/issues/detail?id=979131)
- [ ] [Issue 980121: Regression: Print system dialog is not visible in full screen mode after clicking on 'Print Summary' option of Audit.](https://bugs.chromium.org/p/chromium/issues/detail?id=980121)
- [ ] [Issue 976561: Regression: Emulated window overlaps with dev-tools window on resizing.](https://bugs.chromium.org/p/chromium/issues/detail?id=976561#c2)

# Not specific to DevTools

## Moderate

- [x] #9142 Large URLs make for a funky topbar
- [ ] #9143 Performance anchor positions page in odd spot.
- [x] #9167 Dual focus b/wn sticky header score gauge + highlighter
- [x] #9168 Tools menu steals tab focus even when collapsed
- [ ] [Issue 972523: Regression: [DevTools] Unable to enable/disable the expand/collapse button on pressing 'Enter' key under Audits section.](https://bugs.chromium.org/p/chromium/issues/detail?id=972523)
- [ ] [Issue 980491: Regression: Lighthouse icon changes its size while resizing the devtools window.](https://bugs.chromium.org/p/chromium/issues/detail?id=980491)
- [ ] [Issue 980890: Regression: "Accessibility" text is seen overlapping with Accessibility meter on Print Preview page.](https://bugs.chromium.org/p/chromium/issues/detail?id=980890)

## meh

- [ ] Flickering on scroll #9141
- [ ] [Issue 971555: Regression: Unnecessary blue focus is seen around the 'Expand/collapse' performance metrics button on mouse click.](https://bugs.chromium.org/p/chromium/issues/detail?id=971555)
- [ ] [Issue 971599: Regression:Blue focus ring on 'passed audit' result is not center aligned.](https://bugs.chromium.org/p/chromium/issues/detail?id=971599)
- [ ] [Issue 972975: Regression: Blue focus highlight is not seen properly on Audit result icons.](https://bugs.chromium.org/p/chromium/issues/detail?id=972975)
- [ ] [Issue 973775: Regression:Black underline is seen misplaced on clicking over audit result icons.](https://bugs.chromium.org/p/chromium/issues/detail?id=973775)
- [ ] [Issue 976617: Regression:Unable to tab focus over the dark mode theme icon in devtools.](https://bugs.chromium.org/p/chromium/issues/detail?id=976617)
- [ ] [Issue 979134: Regression: [DevTools] 'Export report' overlay of Audit doesn't dismiss after pressing 'Esc' key](https://bugs.chromium.org/p/chromium/issues/detail?id=979134)
- [ ] [Issue 982174: Regression: 'Export report menu' contents are seen chopped on changing 'font size' to Very Large.](https://bugs.chromium.org/p/chromium/issues/detail?id=982174)
- [ ] [large font size makes score gauges numbers overlap with gauge](https://bugs.chromium.org/p/chromium/issues/detail?id=985707)

**Comment by connorjclark** [comment]
I triaged.

**Comment by connorjclark** [comment]
Branch point is this upcoming Thursday (25th). Should try to fix the bad ones before then.
