### ISSUE TITLE
[meta] Lighthouse 6.0 Burndown

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#9774]
Channeling our [ancestors](https://github.com/GoogleChrome/lighthouse/issues/8331), we introduce the new abbreviated major release burndown list.

## 6.0 final scope

- [x] (see all: https://github.com/GoogleChrome/lighthouse/labels/6.0)
- [x] T&S added as a group to BP [@Beytoven] (PR #10623)
- [x] add "mixed content" wording into "https" (PR #10712) [@Beytoven]
- [ ] new metrics actionability
- - [x] LCP #10517
- - [x] CLS #10702
- - [x] long tasks #10736
- [x] window.location for finalUrl [@paulirish, @patrickhulce] (PR #10339)
- [x] add desktop scoring curves to LCP/TBT [@brendankenny] (PR #10756)
- [x] roll 1.0.0 of adspeed plugin [@paulirish]

## Punting to 6.1
- [ ] fold experimental config into default? [@connorjclark]

## 6.0-beta.0 scope 
(need to triage a bit )

### New audits
- Total Blocking Time
  - [x] land it (PRs #8975, #9409)
  - [x] Update score curve from HTTPArchive distributions [@brendankenny]
  - [x] web.dev docs (https://github.com/GoogleChrome/web.dev/issues/1627)
- Largest Contentful Paint
  - [x] Land observed impl (PR #9706)
  - [x] Land lantern impl/audit [@connorjclark]
  - [x] web.dev docs (https://github.com/GoogleChrome/web.dev/pull/1639)
- New axe audits #7127
  - [x] land new audits (PR #9798) [@brendankenny]
  - [x] web.dev docs (https://github.com/GoogleChrome/web.dev/issues/1629)
- Cumulative Layout Shift
  - [x] land it (PR #9037) [@paulirish]
  - [x] make decisions about it :)

### Lantern
- [ ] "Fixed RTT" calculation [@paulirish]
- [x] Keep first paint events (#9627) [@connorjclark]
- [x] Remove min task duration #9910 [@warrengm]
- [x] data URI server response time (#9833) [@patrickhulce] 

### Scoring
- [x] check latest HTTPArchive distributions for major drift from current metric score curves [@brendankenny]
- [x] apply new LH 6.0 score weightings [@paulirish]
   - [x] deprecate any existing metrics [@paulirish]
- [x] desktop curves #9436 [@connorjclark ]
- [x] revise scoring documentation (https://github.com/GoogleChrome/web.dev/issues/1630) [@kaycebasques]
   - [x] take another pass [on this](https://github.com/GoogleChrome/web.dev/pull/1660) and merge in work from [here](https://github.com/google/WebFundamentals/compare/master...paulirish:v5scoringscreenshot) and probably [here](https://github.com/GoogleChrome/web.dev/pull/977)  [@paulirish]
   - [x] these docs need to be updated https://github.com/GoogleChrome/lighthouse/blob/d2ec9ffbb21de9ad1a0f86ed24575eda32c796f0/docs/scoring.md#how-are-the-scores-weighted
- ~Move PWA fastenough check to use TBT instead?~ Punting for now and keeping it dependent on TTI. Moving to TBT doesn't appear to be a clear win.

### New gatherers
- [x] `main-document-content` #9756 (PR #9781) [@brendankenny]

### Core misc
- [x] iframe page dependency fix (PR #9727) [@patrickhulce]
- ~redirect/first vs last navstart cleanups #8984 [@brendankenny]~ #10339 handled the part we wanted for 6.0
- [x] nexus 5x -> moto g4 labeling change [@connorjclark]
- ~i18n plugin things~ 

### Lighthouse CI [@patrickhulce]
- [x] MVP burndown list: https://github.com/GoogleChrome/lighthouse-ci/issues/9

### Extension
- [x] retire the full-LH extension (PR #9193) [@connorjclark]

### DevTools [@connorjclark]
- [x] Add device emulation flag #9377
- [x] New design / Throttling removal / logo
- [x] [OOPIFs in DevTools Audits panel are not analyzed](https://bugs.chromium.org/p/chromium/issues/detail?id=1011228)
- [x] Write throttling Learn More doc [cjamcl, paulirish]

### PSI
- [x] New field data [thresholds](https://goto.google.com/xpa-thresholds) [@paulirish]
- [x] reanalyze prompt. redirect & amp [@exterkamp]
- [ ] Make comms for v6.0.0 PSI scoring changes [@egsweeny]

### Plugins
- [ ] QoL improvements #9052 [@paulirish]
- [ ] Write Plugins learn more doc [@egsweeny]
- [x] "Community plugins beta" in DevTools [@connorjclark]
  - [x] build step [@brendankenny]

### Budgets
- [x] Add timing budgets #8917 [@khempenius]

### Stack Packs
- [x] Pick and merge new packs from [lighthouse-stack-packs](https://github.com/GoogleChrome/lighthouse-stack-packs) (PR #9797) [@exterkamp]
- [x] i18n strings [@exterkamp]

# Puntable

### Core breaking changes (#9180)
- [ ] Remove path support for `--extra-headers` (and possibly `budget-path`?) as now users can use `cli-flags-path`
- [ ] (possibly) remove `maxWaitForFcp` timeout and look directly for the early load-failure cases (DNS, bad cert, etc) - https://github.com/GoogleChrome/lighthouse/pull/9509#issuecomment-518408375
- ~outstanding i18n tasks? #7238 [@exterkamp]~ none for 6.0
- ~(possibly) refactor i18n section in proto to use Map<string, string> instead of RendererFormattedStrings~

### Report
- [ ] mobile or desktop run indicator at the top of the report #9379

**Comment by addyosmani** [comment]
Thanks for putting together the 6.0 burndown list, @brendankenny! Are we planning to create issues for tracking the rest of the items here? (e.g scoring seems light :))

**Comment by brendankenny** [comment]
> Thanks for putting together the 6.0 burndown list, @brendankenny! Are we planning to create issues for tracking the rest of the items here? (e.g scoring seems light :))

yes, any and all of these can be expanded in here based on how the work can be split up and in separate issues if they need more discussion. We can definitely do JIT expansion based on where discussion is needed...for many of these PR review is sufficient, for others (like scoring) there are other discussions going on that may end up finding a home in a new issue.

But please do open issues and expand bullet points as you see fit.

**Comment by rockeynebhwani** [comment]
@paulirish / @addyosmani - Is there a timeline for LightHouse 6.0 to be released?

**Comment by zakharow** [comment]
> @paulirish / @addyosmani - Is there a timeline for LightHouse 6.0 to be released?

+1

**Comment by connorjclark** [comment]
6.0 is LIVE.
