### ISSUE TITLE
:umbrella: release script improvements

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9857]
- [x] smokehouse tmp directory breaks test.sh (#9855)
- [ ] devtools: add `git commit` with the expected commit message filled out
- [ ] devtools: kick of CQ from CLI
- [ ] lr: internal roll script does not use lighthouse-pristine. this is fine when used for development, but when using to roll a release the script should use pristine
- [ ] sed doesn't work in linux. Instead of fixing this, I think the scripts should be rewritten in Node
- [ ] new contributors should show github names. there may be no API for this, at the least we should log the links to the PRs of new contributors so the usernames can be quickly found
- [ ] new contributors script showed a duplicate https://github.com/GoogleChrome/lighthouse/pull/9856#discussion_r336215268
- [ ] changelog category order should be specified based on the adhoc ordering we've done (by importance)
- [ ] changelog generator should include "We expect this release to ship in the DevTools of Chrome XX." with a link to the chrome release dashboard.

**Comment by connorjclark** [comment]
> sed doesn't work in linux. Instead of fixing this, I think the scripts should be rewritten in Node

@patrickhulce WDYT of this?

**Comment by patrickhulce** [comment]
> sed doesn't work in linux.

I'm not sure I believe this statement :) but if you feel it's much easier to accomplish all of this in node then sure let's go for it! the goal of these scripts are to reduce the burden on the releaser as much as possible so whatever accomplishes that SGTM

**Comment by connorjclark** [comment]
I elided the important info. We use a sed extension that is only standard on Mac.
